'use client';
import { FormEvent, useEffect, useState } from 'react';
import { activateWhatsAppProvider, createTemplate, createWhatsAppProvider, deleteWhatsAppProvider, getSystemSettings, listTemplates, listWhatsAppProviders, submitTemplate, syncTemplates, testWhatsAppProvider, updateSystemSettings } from '../../../lib/api';
import { SystemSettingsPayload, WhatsAppProvider, WhatsAppTemplate } from '../../../lib/types';
import ProvidersTab from '@/components/settings/whatsapp-business/ProvidersTab';
import TemplatesTab from '@/components/settings/whatsapp-business/TemplatesTab';

const INITIAL_FORM: SystemSettingsPayload = { token: '', phone_number_id: '', webhook_url: '', webhook_status: 'inactive', system_name: '', language: 'pt-BR' };
const baseProviderForm={provider_type:'meta_cloud',display_name:'',waba_id:'',phone_number_id:'',business_id:'',access_token:'',api_key:''};
const baseTemplateForm={name:'',category:'utility',language:'pt_BR',body_text:'',footer_text:''};
export default function SettingsPage(){
const [tab,setTab]=useState<'system'|'connection'|'templates'>('system'); const [toast,setToast]=useState(''); const [loading,setLoading]=useState(false);
const [form,setForm]=useState<SystemSettingsPayload>(INITIAL_FORM); const [providers,setProviders]=useState<WhatsAppProvider[]>([]); const [templates,setTemplates]=useState<WhatsAppTemplate[]>([]);
const [providerForm,setProviderForm]=useState(baseProviderForm); const [templateForm,setTemplateForm]=useState(baseTemplateForm); const [templateError,setTemplateError]=useState('');
const refresh=async()=>{setProviders(await listWhatsAppProviders());setTemplates(await listTemplates());}
useEffect(()=>{(async()=>{const data=await getSystemSettings();setForm({...INITIAL_FORM,...data});await refresh();})()},[]);
const validateTemplate=()=>{if(!/^[a-z0-9_]+$/.test(templateForm.name)) return 'Nome do template deve ter lowercase e underscores.'; const re=/\{\{(\d+)\}\}/g; const m:number[]=[]; let hit; while((hit=re.exec(templateForm.body_text))!==null){m.push(Number(hit[1]));} const set=new Set(m); if(set.size!==m.length) return 'Variáveis duplicadas não são permitidas.'; for(let i=1;i<=m.length;i++) if(!set.has(i)) return 'Variáveis com buracos são inválidas. Ex: {{1}} {{3}}'; return '';}
async function run(action:()=>Promise<void>,ok:string,err:string){setLoading(true);try{await action();setToast(ok)}catch{setToast(err)}finally{setLoading(false);setTimeout(()=>setToast(''),3000)}}
return <section className='w-full min-w-0 px-6 py-6'><div className='max-w-6xl mx-auto space-y-4'><h1 className='text-2xl font-semibold'>Configurações · WhatsApp Business</h1>{toast&&<div className='settings-card p-3'>{toast}</div>}<div className='flex gap-2'>{['system','connection','templates'].map(t=><button key={t} className='secondary-button' onClick={()=>setTab(t as any)}>{t}</button>)}</div>
{tab==='system'&&<form onSubmit={(e:FormEvent)=>run(async()=>{e.preventDefault();await updateSystemSettings({...form,token:form.token||null,phone_number_id:form.phone_number_id||null,webhook_url:form.webhook_url||null});},'Configurações salvas com sucesso','Falha ao salvar configurações')} className='settings-card p-4 space-y-3'><input type='password' value={form.token??''} onChange={e=>setForm(p=>({...p,token:e.target.value}))} placeholder='Token atual (ENV fallback preservado)'/><input value={form.phone_number_id??''} onChange={e=>setForm(p=>({...p,phone_number_id:e.target.value}))} placeholder='Phone Number ID'/><button disabled={loading} className='primary-button'>Salvar</button></form>}
{tab==='connection'&&<ProvidersTab providers={providers} form={providerForm} setForm={setProviderForm} loading={loading} onSubmit={(e:FormEvent)=>run(async()=>{e.preventDefault();await createWhatsAppProvider(providerForm);setProviderForm(baseProviderForm);await refresh();},'Conexão salva com sucesso','Falha ao salvar conexão')} onTest={(id:string)=>run(async()=>{await testWhatsAppProvider(id);await refresh();},'Conexão testada com sucesso','Falha ao testar conexão')} onActivate={(id:string)=>run(async()=>{await activateWhatsAppProvider(id);await refresh();},'Conexão ativada com sucesso','Falha ao ativar conexão')} onDelete={(id:string)=>run(async()=>{await deleteWhatsAppProvider(id);await refresh();},'Conexão removida com sucesso','Falha ao remover conexão')} />}
{tab==='templates'&&<TemplatesTab templates={templates} form={templateForm} setForm={setTemplateForm} error={templateError} loading={loading} onSubmit={(e:FormEvent)=>run(async()=>{e.preventDefault();const msg=validateTemplate();setTemplateError(msg);if(msg) throw new Error(msg);await createTemplate(templateForm);setTemplateForm(baseTemplateForm);await refresh();},'Template criado com sucesso','Falha ao criar template')} onSync={()=>run(async()=>{await syncTemplates();await refresh();},'Sincronização concluída','Erro ao sincronizar templates')} onSubmitTemplate={(id:string)=>run(async()=>{await submitTemplate(id);await refresh();},'Template enviado para aprovação','Falha ao enviar template')} />}
</div></section>}
