from __future__ import annotations

from enum import StrEnum


class TraceEventType(StrEnum):
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    TENANT_RESOLVED = "TENANT_RESOLVED"
    JOB_ENQUEUED = "JOB_ENQUEUED"
    WORKER_STARTED = "WORKER_STARTED"
    FLOW_SELECTED = "FLOW_SELECTED"
    NODE_EXECUTED = "NODE_EXECUTED"
    NODE_FAILED = "NODE_FAILED"
    AI_AGENT_STARTED = "AI_AGENT_STARTED"
    AI_AGENT_FINISHED = "AI_AGENT_FINISHED"
    SUPERVISOR_STARTED = "SUPERVISOR_STARTED"
    SUPERVISOR_FINISHED = "SUPERVISOR_FINISHED"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_FINISHED = "TOOL_FINISHED"
    MCP_DISCOVERY_STARTED = "MCP_DISCOVERY_STARTED"
    MCP_DISCOVERY_FINISHED = "MCP_DISCOVERY_FINISHED"
    MCP_CALLED = "MCP_CALLED"
    MCP_FINISHED = "MCP_FINISHED"
    WEBHOOK_CALLED = "WEBHOOK_CALLED"
    WEBHOOK_FINISHED = "WEBHOOK_FINISHED"
    LLM_REQUEST = "LLM_REQUEST"
    LLM_RESPONSE = "LLM_RESPONSE"
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_FAILED = "MESSAGE_FAILED"
    EXECUTION_FINISHED = "EXECUTION_FINISHED"
    EXECUTION_FAILED = "EXECUTION_FAILED"


SUPPORTED_EVENT_TYPES = tuple(item.value for item in TraceEventType)
