"use client";

import { useEffect, useMemo, useState } from "react";
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, Calendar, ChevronDown, Copy, Download, FileText, Search, Send, Users, X } from "lucide-react";
import { listWhatsAppCampaignRecipients } from "@/lib/api";
import { WhatsAppCampaign, WhatsAppCampaignRecipient, WhatsAppTemplate } from "@/lib/types";
import CampaignStatusBadge from "./CampaignStatusBadge";

type Tab = "overview" | "timeline" | "evolution" | "recipients" | "failures" | "template" | "activity";
const tabs: Array<[Tab, string]> = [["overview", "Visão geral"], ["timeline", "Timeline"], ["evolution", "Evolução"], ["recipients", "Destinatários"], ["failures", "Falhas"], ["template", "Template"], ["activity", "Atividades"]];
const fmt = new Intl.NumberFormat("pt-BR");
const date = (value?: string | null) => value ? new Date(value).toLocaleString("pt-BR", { dateStyle: "medium", timeStyle: "short" }) : "—";
const time = (value?: string | null) => value ? new Date(value).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }) : "—";
const percent = (value: number, total: number) => total ? Math.round(value / total * 100) : 0;
const elapsed = (start?: string | null, end?: string | null) => {
  if (!start) return "—"; const minutes = Math.max(0, Math.round(((end ? new Date(end) : new Date()).getTime() - new Date(start).getTime()) / 60000));
  return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)}h ${minutes % 60}min`;
};
function category(error?: string | null) { const value = String(error || "").toLowerCase(); if (value.includes("opt") || value.includes("block")) return "Opt-out"; if (value.includes("template") || value.includes("variável")) return "Template"; if (value.includes("limit") || value.includes("meta")) return "Meta Limit"; if (value.includes("phone") || value.includes("número") || value.includes("invalid")) return "Telefone inválido"; if (value.includes("provider")) return "Provider"; return "Erro interno"; }
function mask(phone: string) { return phone.length > 7 ? `${phone.slice(0, 5)} •••• ${phone.slice(-3)}` : phone; }
function Skeleton({ className = "" }: { className?: string }) { return <div className={`animate-pulse rounded-xl bg-slate-100 ${className}`} />; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/70 px-5 py-10 text-center text-sm text-slate-500">{children}</div>; }

export default function CampaignDetailsDrawer({ campaign, template, onClose, actions, preview = false }: { campaign: WhatsAppCampaign; template?: WhatsAppTemplate; onClose: () => void; actions: React.ReactNode; preview?: boolean }) {
  const [tab, setTab] = useState<Tab>("overview");
  const [recipients, setRecipients] = useState<WhatsAppCampaignRecipient[]>([]);
  const [loading, setLoading] = useState(false);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [openFailure, setOpenFailure] = useState<string | null>(null);
  useEffect(() => { const escape = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", escape); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", escape); document.body.style.overflow = ""; }; }, [onClose]);
  useEffect(() => { if (tab !== "recipients" && tab !== "failures") return; let alive = true; setLoading(true); if (preview) { const states = ["read", "delivered", "sent", "failed"]; const rows = Array.from({ length: Math.min(80, Math.max(16, campaign.total_recipients || 16)) }, (_, index) => ({ id: `preview-${index}`, campaign_id: campaign.id, phone: `+55 11 9${String(80000000 + index).slice(-8)}`, first_name: `Contato ${index + 1}`, status: states[index % 4], sent_at: campaign.started_at, delivered_at: index % 4 < 2 ? campaign.started_at : null, read_at: index % 4 === 0 ? campaign.completed_at || campaign.started_at : null, failed_at: index % 4 === 3 ? campaign.started_at : null, error_message: index % 4 === 3 ? ["Telefone inválido", "Opt-out do destinatário", "Meta limit exceeded", "Template variable inválida"][index % 4] : null })); if (alive) { setRecipients(rows); setLoading(false); } return () => { alive = false; }; }
    listWhatsAppCampaignRecipients(campaign.id).then(rows => { if (alive) setRecipients(rows); }).catch(() => { if (alive) setRecipients([]); }).finally(() => alive && setLoading(false)); return () => { alive = false; };
  }, [campaign.id, campaign.total_recipients, campaign.started_at, campaign.completed_at, preview, tab]);
  const failures = useMemo(() => recipients.filter(row => row.status.includes("failed")).reduce<Record<string, WhatsAppCampaignRecipient[]>>((result, row) => { const key = category(row.error_message); (result[key] ||= []).push(row); return result; }, {}), [recipients]);
  const displayed = useMemo(() => recipients.filter(row => (status === "all" || row.status.includes(status)) && `${row.first_name || ""} ${row.phone}`.toLowerCase().includes(query.toLowerCase())), [query, recipients, status]);
  const timeline = useMemo(() => { const start = campaign.started_at ? new Date(campaign.started_at).getTime() : Date.now() - 20 * 60000; const finish = campaign.completed_at ? new Date(campaign.completed_at).getTime() : start + 20 * 60000; return [0, .15, .35, .6, .8, 1].map((part, i) => ({ bucket: new Date(start + (finish - start) * part).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }), sent: Math.round((campaign.total_sent || 0) * part), delivered: Math.round((campaign.total_delivered || 0) * part), read: Math.round((campaign.total_read || 0) * Math.max(0, part - .12) / .88), failed: Math.round((campaign.total_failed || 0) * part), key: i })); }, [campaign]);
  const events = [["Campanha criada", campaign.created_at], ["Agendada", campaign.scheduled_at], ["Worker iniciado", campaign.started_at], ["Primeiros envios", campaign.started_at], [`${fmt.format(campaign.total_sent || 0)} enviadas`, campaign.started_at], ["Concluída", campaign.completed_at]].filter((item): item is [string, string] => Boolean(item[1]));
  const totals = [["Enviadas", campaign.total_sent || 0, "bg-slate-700"], ["Entregues", campaign.total_delivered || 0, "bg-emerald-500"], ["Lidas", campaign.total_read || 0, "bg-indigo-500"], ["Falhas", campaign.total_failed || 0, "bg-rose-500"]] as const;
  const detailRows = [["Status", campaign.status], ["Template", template?.name || campaign.template_id], ["Categoria Meta", template?.category || "—"], ["Idioma", template?.language || "—"], ["Canal", "WhatsApp Business"], ["Remetente", campaign.provider_id], ["Agendada", date(campaign.scheduled_at)], ["Início", date(campaign.started_at)], ["Fim", date(campaign.completed_at)], ["Duração", elapsed(campaign.started_at, campaign.completed_at)], ["Destinatários", fmt.format(campaign.total_recipients || 0)]];
  return <><div aria-hidden="true" onClick={onClose} className="fixed inset-0 z-[80] bg-black/25 opacity-100 transition-opacity" /><aside role="dialog" aria-modal="true" aria-label={`Detalhes de ${campaign.name}`} className="campaign-details-drawer fixed inset-y-0 right-0 z-[81] flex w-full flex-col border-l border-slate-200 bg-white shadow-[-18px_0_60px_-25px_rgba(15,23,42,.45)] md:max-w-[720px]">
    <header className="border-b border-slate-100 px-5 py-5 sm:px-6"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-semibold tracking-tight text-slate-950">{campaign.name}</h2><CampaignStatusBadge status={campaign.status} /></div><p className="mt-1 truncate text-sm text-slate-500">{template?.name || campaign.template_id} · <span className="font-medium">WhatsApp Business</span></p></div><button type="button" onClick={onClose} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-slate-200 text-slate-500 transition hover:bg-slate-50 hover:text-slate-900" aria-label="Fechar detalhes"><X size={18} /></button></div><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 text-xs text-slate-500 sm:grid-cols-4"><span><Calendar className="mr-1 inline h-3.5 w-3.5" />Criada: {date(campaign.created_at)}</span><span>Iniciada: {time(campaign.started_at)}</span><span>Finalizada: {time(campaign.completed_at)}</span><span>Duração: {elapsed(campaign.started_at, campaign.completed_at)}</span></div></header>
    <section className="grid grid-cols-2 gap-2 border-b border-slate-100 px-5 py-4 sm:grid-cols-4 sm:px-6">{totals.map(([label, value, color]) => <div key={label} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-3"><span className={`mb-2 block h-1.5 w-8 rounded-full ${color}`} /><p className="text-xl font-semibold tabular-nums text-slate-950">{fmt.format(value)}</p><p className="text-xs font-medium text-slate-500">{label}</p></div>)}</section>
    <nav className="flex shrink-0 gap-1 overflow-x-auto border-b border-slate-100 px-5 sm:px-6">{tabs.map(([id, label]) => <button type="button" key={id} onClick={() => setTab(id)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-medium transition ${tab === id ? "border-emerald-600 text-emerald-700" : "border-transparent text-slate-500 hover:text-slate-900"}`}>{label}</button>)}</nav>
    <main className="min-h-0 flex-1 overflow-y-auto px-5 py-5 sm:px-6">
      {tab === "overview" && <div className="space-y-5"><section className="grid gap-2 sm:grid-cols-2">{detailRows.map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-100 p-3.5"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-900">{value}</p></div>)}</section><section className="rounded-2xl border border-slate-100 p-4"><h3 className="font-semibold text-slate-900">Performance da campanha</h3><div className="mt-4 space-y-4">{[["Entrega", campaign.total_delivered || 0, campaign.total_sent || 0, "bg-emerald-500"], ["Leitura", campaign.total_read || 0, campaign.total_delivered || 0, "bg-indigo-500"], ["Falhas", campaign.total_failed || 0, campaign.total_recipients || 0, "bg-rose-500"]].map(([label, value, total, color]) => <div key={label}><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium text-slate-600">{label}</span><span className="font-semibold text-slate-900">{percent(value as number, total as number)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${percent(value as number, total as number)}%` }} /></div></div>)}</div></section></div>}
      {tab === "timeline" && <section>{events.length ? <ol className="relative ml-2 border-l border-slate-200 pl-6">{events.map(([label, value], index) => <li key={`${label}-${index}`} className="relative pb-7 last:pb-0"><span className="absolute -left-[31px] top-0.5 h-3 w-3 rounded-full border-[3px] border-white bg-emerald-500 shadow" /><p className="font-semibold text-slate-900">{label}</p><p className="mt-1 text-xs text-slate-500">{date(value)}</p></li>)}</ol> : <Empty>A linha do tempo aparecerá assim que a campanha registrar atividades.</Empty>}</section>}
      {tab === "evolution" && <section className="rounded-2xl border border-slate-100 p-4"><div className="mb-4 flex items-center gap-2"><BarChart3 className="text-emerald-600" size={18}/><div><h3 className="font-semibold text-slate-900">Evolução operacional</h3><p className="text-xs text-slate-500">Acumulado durante a execução da campanha.</p></div></div><div className="h-[300px]">{campaign.total_recipients ? <ResponsiveContainer width="100%" height="100%"><ComposedChart data={timeline}><defs><linearGradient id="drawerSent" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#10b981" stopOpacity=".22"/><stop offset="100%" stopColor="#10b981" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="bucket" tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false}/><Tooltip /><Area type="monotone" dataKey="sent" name="Enviadas" stroke="#059669" fill="url(#drawerSent)" strokeWidth={2}/><Line type="monotone" dataKey="delivered" name="Entregues" stroke="#2563eb" dot={false} strokeWidth={2}/><Line type="monotone" dataKey="read" name="Lidas" stroke="#4f46e5" dot={false} strokeWidth={2}/><Line type="monotone" dataKey="failed" name="Falhas" stroke="#e11d48" dot={false} strokeWidth={2}/></ComposedChart></ResponsiveContainer> : <Empty>Os dados de evolução estarão disponíveis quando houver envios.</Empty>}</div></section>}
      {(tab === "recipients" || tab === "failures") && loading && <div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-14 w-full" />)}</div>}
      {tab === "recipients" && !loading && <section><div className="mb-3 flex flex-wrap gap-2"><label className="relative min-w-[200px] flex-1"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar nome ou telefone" className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-emerald-500" /></label>{[["all", "Todos"], ["sent", "Enviadas"], ["delivered", "Entregues"], ["read", "Lidas"], ["failed", "Falhas"]].map(([id,label]) => <button key={id} onClick={() => setStatus(id)} className={`rounded-xl px-3 text-xs font-semibold ${status === id ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-600"}`}>{label}</button>)}</div>{displayed.length ? <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[650px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-400"><tr><th className="p-3">Nome</th><th>Telefone</th><th>Status</th><th>Hora</th><th>Tempo</th></tr></thead><tbody className="divide-y divide-slate-100">{displayed.slice(0, 50).map(row => { const at = row.read_at || row.delivered_at || row.failed_at || row.sent_at; return <tr key={row.id}><td className="p-3 font-medium text-slate-900">{row.first_name || "—"}</td><td className="text-slate-600">{mask(row.phone)}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium text-slate-700">{row.status}</span></td><td className="text-slate-600">{time(at)}</td><td className="text-slate-600">{elapsed(row.sent_at, at)}</td></tr>; })}</tbody></table></div> : <Empty>Nenhum destinatário corresponde aos filtros selecionados.</Empty>}</section>}
      {tab === "failures" && !loading && <section className="space-y-2">{Object.keys(failures).length ? Object.entries(failures).map(([name, rows]) => <div key={name} className="overflow-hidden rounded-2xl border border-slate-200"><button onClick={() => setOpenFailure(openFailure === name ? null : name)} className="flex w-full items-center gap-3 p-4 text-left"><span className="flex-1 font-semibold text-slate-900">{name}</span><span className="text-sm font-semibold text-rose-600">{fmt.format(rows.length)} · {percent(rows.length, recipients.length)}%</span><ChevronDown className={`text-slate-400 transition ${openFailure === name ? "rotate-180" : ""}`} size={17}/></button><div className="mx-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-rose-500" style={{ width: `${percent(rows.length, recipients.length)}%` }}/></div>{openFailure === name && <div className="mt-3 border-t border-slate-100 bg-slate-50 p-4 text-sm text-slate-600">Exemplos: {rows.slice(0, 3).map(row => mask(row.phone)).join(", ")}</div>}</div>) : <Empty>Esta campanha não registrou falhas.</Empty>}</section>}
      {tab === "template" && <section className="space-y-3">{template ? <><div className="rounded-2xl border border-slate-100 p-4"><p className="text-xs font-medium text-slate-500">{template.category || "—"} · {template.language}</p><h3 className="mt-1 font-semibold text-slate-950">{template.name}</h3></div><div className="rounded-2xl border border-slate-100 p-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Corpo</p><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{template.body_text || template.body_preview || "Sem corpo disponível."}</p></div>{template.variables_json?.length ? <div className="rounded-2xl border border-slate-100 p-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Variáveis</p>{template.variables_json.map(v => <p key={v.position} className="text-sm text-slate-700">{`{{${v.position}}}`} <span className="text-slate-500">— {v.label || v.key}</span></p>)}</div> : null}</> : <Empty>O template utilizado não está mais disponível neste workspace.</Empty>}</section>}
      {tab === "activity" && <section className="space-y-2">{[["Criado", campaign.created_at], ["Atualizado", campaign.updated_at], ["Iniciado", campaign.started_at], ["Concluído", campaign.completed_at]].filter(([, value]) => value).map(([label, value]) => <div key={label} className="flex justify-between rounded-2xl border border-slate-100 p-4"><span className="font-medium text-slate-800">{label}</span><span className="text-sm text-slate-500">{date(value)}</span></div>)}<div className="rounded-2xl border border-slate-100 p-4 text-sm text-slate-600">Worker e fila: disponíveis durante a execução da campanha.</div></section>}
    </main><footer className="flex flex-wrap items-center gap-2 border-t border-slate-100 bg-white px-5 py-4 sm:px-6"><button className="secondary-button inline-flex items-center gap-1.5"><Copy size={14}/>Duplicar</button><button className="secondary-button inline-flex items-center gap-1.5"><FileText size={14}/>Abrir template</button><button className="secondary-button inline-flex items-center gap-1.5"><Download size={14}/>Exportar</button><div className="ml-auto flex gap-2">{actions}<button onClick={onClose} className="secondary-button">Fechar</button></div></footer>
  </aside></>;
}
