"""Add internal product analytics tables.
Revision ID: 20260723_product_analytics
Revises: 20260721_billing_usage
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='20260723_product_analytics'; down_revision='20260721_billing_usage'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('product_events',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('event_id',postgresql.UUID(as_uuid=True),nullable=False),sa.Column('tenant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('tenants.id',ondelete='CASCADE')),sa.Column('user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('tenant_users.id',ondelete='SET NULL')),sa.Column('session_id',sa.String(128)),sa.Column('anonymous_id',sa.String(128)),sa.Column('event_name',sa.String(96),nullable=False),sa.Column('event_version',sa.Integer(),nullable=False,server_default='1'),sa.Column('source',sa.String(24),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False),sa.Column('received_at',sa.DateTime(timezone=True),nullable=False),sa.Column('properties',postgresql.JSONB(),nullable=False,server_default='{}'),sa.Column('context',postgresql.JSONB(),nullable=False,server_default='{}'),sa.Column('idempotency_key',sa.String(255)),sa.Column('request_id',sa.String(128)),sa.Column('correlation_id',sa.String(128)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('event_id',name='uq_product_events_event_id'))
 for name,cols in [('ix_product_events_tenant_id',['tenant_id']),('ix_product_events_user_id',['user_id']),('ix_product_events_event_name',['event_name']),('ix_product_events_occurred_at',['occurred_at']),('ix_product_events_idempotency_key',['idempotency_key']),('ix_product_events_tenant_event_time',['tenant_id','event_name','occurred_at'])]:op.create_index(name,'product_events',cols)
 op.create_table('product_metric_daily',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('date',sa.Date(),nullable=False),sa.Column('tenant_id',postgresql.UUID(as_uuid=True)),sa.Column('metric_name',sa.String(96),nullable=False),sa.Column('dimension_key',sa.String(64),nullable=False,server_default='all'),sa.Column('dimension_value',sa.String(128),nullable=False,server_default='all'),sa.Column('metric_value',sa.Float(),nullable=False,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('date','tenant_id','metric_name','dimension_key','dimension_value',name='uq_product_metric_daily'))
 op.create_table('tenant_activation_state',sa.Column('tenant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('tenants.id',ondelete='CASCADE'),primary_key=True),*[sa.Column(n,sa.DateTime(timezone=True)) for n in 'registration_completed_at trial_started_at onboarding_started_at onboarding_completed_at whatsapp_connected_at first_conversation_at first_flow_created_at first_flow_published_at first_message_received_at first_message_sent_at first_ai_execution_at first_mcp_execution_at first_observability_view_at billing_page_opened_at upgrade_clicked_at checkout_started_at subscription_activated_at activation_completed_at'.split()],sa.Column('activation_score',sa.Integer(),nullable=False,server_default='0'),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
def downgrade():
 op.drop_table('tenant_activation_state');op.drop_table('product_metric_daily');op.drop_table('product_events')
