"""Add the non-enforcing billing, subscription, and entitlement foundation.

Revision ID: 20260721_billing_foundation
Revises: 20260719_wp_auth_type
Create Date: 2026-07-21
"""
import uuid
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260721_billing_foundation"
down_revision = "20260719_wp_auth_type"
branch_labels = None
depends_on = None

FEATURES = ("dashboard", "inbox", "crm", "pipeline", "flows", "integrations", "academy", "users", "whatsapp_numbers", "published_flows", "monthly_conversations", "monthly_messages", "monthly_flow_executions", "storage_bytes", "ai_enabled", "ai_agent", "ai_system", "ai_memory", "ai_playground", "ai_rag", "ai_monthly_credit_cents", "mcp", "api_access", "webhooks", "google_calendar", "observability", "observability_retention_days", "observability_exports", "observability_replay", "observability_infrastructure", "advanced_roles", "audit", "sso", "priority_support")
PLAN_IDS = {code: uuid.uuid5(uuid.NAMESPACE_URL, f"wazza:billing-plan:{code}") for code in ("starter", "growth", "business", "enterprise", "legacy")}

def upgrade() -> None:
    op.create_table("plans", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("code", sa.String(64), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("description", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("is_public", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"), sa.Column("monthly_price_cents", sa.Integer()), sa.Column("annual_price_cents", sa.Integer()), sa.Column("currency", sa.String(3), nullable=False, server_default="BRL"), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("code", name="uq_plans_code"))
    op.create_index("ix_plans_code", "plans", ["code"])
    op.create_table("plan_features", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("plans.id", ondelete="CASCADE"), nullable=False), sa.Column("feature_key", sa.String(100), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("limit_value", sa.Integer()), sa.Column("limit_unit", sa.String(48)), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("plan_id", "feature_key", name="uq_plan_features_plan_feature"))
    op.create_index("ix_plan_features_plan_id", "plan_features", ["plan_id"]); op.create_index("ix_plan_features_feature_key", "plan_features", ["feature_key"])
    op.create_table("subscriptions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False), sa.Column("plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("plans.id"), nullable=False), sa.Column("provider", sa.String(32), nullable=False, server_default="internal"), sa.Column("status", sa.String(32), nullable=False, server_default="legacy"), sa.Column("billing_interval", sa.String(16)), sa.Column("trial_started_at", sa.DateTime()), sa.Column("trial_ends_at", sa.DateTime()), sa.Column("current_period_start", sa.DateTime()), sa.Column("current_period_end", sa.DateTime()), sa.Column("grace_period_ends_at", sa.DateTime()), sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("canceled_at", sa.DateTime()), sa.Column("external_customer_id", sa.String(255)), sa.Column("external_subscription_id", sa.String(255)), sa.Column("external_price_id", sa.String(255)), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("tenant_id", name="uq_subscriptions_tenant"))
    op.create_index("ix_subscriptions_tenant_id", "subscriptions", ["tenant_id"]); op.create_index("ix_subscriptions_tenant_effective", "subscriptions", ["tenant_id", "status"])
    op.create_table("tenant_entitlements", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False), sa.Column("feature_key", sa.String(100), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("limit_value", sa.Integer()), sa.Column("source", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime()), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("tenant_id", "feature_key", "source", name="uq_tenant_entitlements_source"))
    op.create_index("ix_tenant_entitlements_tenant_id", "tenant_entitlements", ["tenant_id"]); op.create_index("ix_tenant_entitlements_tenant_feature", "tenant_entitlements", ["tenant_id", "feature_key"])
    now = datetime.utcnow()
    plans = [("starter", "Starter", "Plano inicial configurável.", True, True, 1, 19700), ("growth", "Growth", "Plano de crescimento configurável.", True, True, 2, 49700), ("business", "Business", "Plano avançado configurável.", True, True, 3, 99700), ("enterprise", "Enterprise", "Sob consulta.", True, True, 4, None), ("legacy", "Acesso legado", "Acesso integral preservado durante a implantação dos novos planos.", True, False, 99, None)]
    bind = op.get_bind()
    plan_table = sa.table("plans", sa.column("id", postgresql.UUID(as_uuid=True)), sa.column("code", sa.String()), sa.column("name", sa.String()), sa.column("description", sa.Text()), sa.column("is_active", sa.Boolean()), sa.column("is_public", sa.Boolean()), sa.column("sort_order", sa.Integer()), sa.column("monthly_price_cents", sa.Integer()), sa.column("annual_price_cents", sa.Integer()), sa.column("currency", sa.String()), sa.column("metadata_json", postgresql.JSONB()), sa.column("created_at", sa.DateTime()), sa.column("updated_at", sa.DateTime()))
    bind.execute(plan_table.insert(), [{"id": PLAN_IDS[code], "code": code, "name": name, "description": desc, "is_active": active, "is_public": public, "sort_order": order, "monthly_price_cents": price, "annual_price_cents": None, "currency": "BRL", "metadata_json": {}, "created_at": now, "updated_at": now} for code, name, desc, active, public, order, price in plans])
    feature_table = sa.table("plan_features", sa.column("id", postgresql.UUID(as_uuid=True)), sa.column("plan_id", postgresql.UUID(as_uuid=True)), sa.column("feature_key", sa.String()), sa.column("enabled", sa.Boolean()), sa.column("limit_value", sa.Integer()), sa.column("limit_unit", sa.String()), sa.column("metadata_json", postgresql.JSONB()), sa.column("created_at", sa.DateTime()), sa.column("updated_at", sa.DateTime()))
    limits = {"starter": {"users": 2, "whatsapp_numbers": 1, "published_flows": 5, "observability_retention_days": 7}, "growth": {"users": 5, "whatsapp_numbers": 1, "published_flows": 20, "observability_retention_days": 30}, "business": {"users": 15, "whatsapp_numbers": 3, "published_flows": 100, "observability_retention_days": 90}}
    enabled = {"starter": {"dashboard", "inbox", "crm", "pipeline", "flows", "academy", "ai_enabled", "observability"}, "growth": set(FEATURES) - {"mcp", "ai_rag", "sso"}, "business": set(FEATURES), "enterprise": set(FEATURES), "legacy": set(FEATURES)}
    bind.execute(feature_table.insert(), [{"id": uuid.uuid4(), "plan_id": PLAN_IDS[code], "feature_key": key, "enabled": key in enabled[code], "limit_value": limits.get(code, {}).get(key), "limit_unit": "count" if key in limits.get(code, {}) else None, "metadata_json": {}, "created_at": now, "updated_at": now} for code in PLAN_IDS for key in FEATURES])
    tenant_ids = [row[0] for row in bind.execute(sa.text("SELECT id FROM tenants"))]
    subscriptions = sa.table("subscriptions", sa.column("id", postgresql.UUID(as_uuid=True)), sa.column("tenant_id", postgresql.UUID(as_uuid=True)), sa.column("plan_id", postgresql.UUID(as_uuid=True)), sa.column("provider", sa.String()), sa.column("status", sa.String()), sa.column("cancel_at_period_end", sa.Boolean()), sa.column("metadata_json", postgresql.JSONB()), sa.column("created_at", sa.DateTime()), sa.column("updated_at", sa.DateTime()))
    if tenant_ids: bind.execute(subscriptions.insert(), [{"id": uuid.uuid4(), "tenant_id": tenant_id, "plan_id": PLAN_IDS["legacy"], "provider": "internal", "status": "legacy", "cancel_at_period_end": False, "metadata_json": {"migration": "20260721_billing_foundation"}, "created_at": now, "updated_at": now} for tenant_id in tenant_ids])

def downgrade() -> None:
    # Only use before commercial data is written; this intentionally removes Phase 1 billing data.
    op.drop_table("tenant_entitlements"); op.drop_table("subscriptions"); op.drop_table("plan_features"); op.drop_table("plans")
