"""init

Revision ID: 4b9289cdf707
Revises: b04725cee6d1
Create Date: 2026-04-30 19:11:04.380235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b9289cdf707'
down_revision: Union[str, Sequence[str], None] = 'b04725cee6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_sessions', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flow_sessions', 'user_identifier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flow_sessions', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.create_index(op.f('ix_flow_sessions_user_identifier'), 'flow_sessions', ['user_identifier'], unique=False)
    op.alter_column('flow_versions', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_flow_versions_is_published'), 'flow_versions', ['is_published'], unique=False)
    op.create_index(op.f('ix_flow_versions_tenant_id'), 'flow_versions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'flow_versions', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flow_versions', type_='foreignkey')
    op.drop_index(op.f('ix_flow_versions_tenant_id'), table_name='flow_versions')
    op.drop_index(op.f('ix_flow_versions_is_published'), table_name='flow_versions')
    op.alter_column('flow_versions', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_flow_sessions_user_identifier'), table_name='flow_sessions')
    op.alter_column('flow_sessions', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('flow_sessions', 'user_identifier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flow_sessions', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
