"""base_clean

Revision ID: b50dc15bdbbe
Revises: 
Create Date: 2026-04-30 06:09:00.967598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50dc15bdbbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='running', nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_sessions_conversation_id'), 'flow_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_flow_sessions_flow_id'), 'flow_sessions', ['flow_id'], unique=False)
    op.create_table('flow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('edges', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_versions_flow_id'), 'flow_versions', ['flow_id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trigger_type', sa.String(), server_default='default', nullable=False),
    sa.Column('trigger_value', sa.String(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('stop_words', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('published_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['flow_versions.id'], ),
    sa.ForeignKeyConstraint(['published_version_id'], ['flow_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_current_version_id'), 'flows', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_flows_published_version_id'), 'flows', ['published_version_id'], unique=False)
    op.create_index(op.f('ix_flows_tenant_id'), 'flows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_flows_trigger_type'), 'flows', ['trigger_type'], unique=False)
    op.create_table('processed_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_processed_messages_tenant_id'), 'processed_messages', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('verify_token', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_token', sa.String(length=512), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_status', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('max_monthly_messages', sa.Integer(), nullable=False),
    sa.Column('usage_month', sa.String(length=7), nullable=False),
    sa.Column('messages_used_month', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.Column('ai_mode', sa.String(length=32), server_default='atendente', nullable=False),
    sa.CheckConstraint("ai_mode IN ('atendente', 'vendedor')", name='ck_tenants_ai_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_phone_number_id'), 'tenants', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_config_id'), 'ai_config', ['id'], unique=False)
    op.create_index(op.f('ix_ai_config_tenant_id'), 'ai_config', ['tenant_id'], unique=True)
    op.create_table('bot_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('match_type', sa.String(length=20), server_default='contains', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_rules_tenant_id'), 'bot_rules', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_contacts_tenant_phone')
    )
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('failed_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('buttons', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_messages_job_id'), 'failed_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_failed_messages_tenant_id'), 'failed_messages', ['tenant_id'], unique=False)
    op.create_table('flow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_nodes_flow_id'), 'flow_nodes', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_nodes_tenant_id'), 'flow_nodes', ['tenant_id'], unique=False)
    op.create_table('flow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('step_key', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected_inputs', postgresql.ARRAY(String()), nullable=True),
    sa.Column('next_step_map', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_steps_flow_id'), 'flow_steps', ['flow_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_tenant_id'), 'knowledge_base', ['tenant_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_pipeline_stage_tenant_name'),
    sa.UniqueConstraint('tenant_id', 'position', name='uq_pipeline_stage_tenant_position')
    )
    op.create_index(op.f('ix_pipeline_stages_tenant_id'), 'pipeline_stages', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('mode', sa.String(length=10), server_default='bot', nullable=False),
    sa.Column('conversation_state', sa.String(), nullable=True),
    sa.Column('current_flow', sa.UUID(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('last_input', sa.String(), nullable=True),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_bot_question', sa.String(), nullable=True),
    sa.Column('current_objective', sa.String(), server_default='venda', nullable=False),
    sa.Column('last_bot_triggered_message_id', sa.UUID(), nullable=True),
    sa.Column('last_intent', sa.String(), nullable=True),
    sa.Column('intent_history', sa.JSON(), nullable=True),
    sa.Column('last_intent_at', sa.DateTime(), nullable=True),
    sa.Column('lead_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['current_flow'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['current_node_id'], ['flow_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.UUID(), nullable=False),
    sa.Column('target', sa.UUID(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['source'], ['flow_nodes.id'], ),
    sa.ForeignKeyConstraint(['target'], ['flow_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_edges_flow_id'), 'flow_edges', ['flow_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('temperature', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_leads_tenant_phone')
    )
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_stage_id'), 'leads', ['stage_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('conversation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('matched_rule', sa.String(), nullable=True),
    sa.Column('flow_step', sa.String(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_logs_conversation_id'), 'conversation_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_tenant_id'), 'conversation_logs', ['tenant_id'], unique=False)
    op.create_table('flow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['flow_nodes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_events_conversation_id'), 'flow_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_flow_events_event_type'), 'flow_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_flow_events_flow_id'), 'flow_events', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_events_node_id'), 'flow_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_flow_events_tenant_id'), 'flow_events', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('from_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_flow_events_tenant_id'), table_name='flow_events')
    op.drop_index(op.f('ix_flow_events_node_id'), table_name='flow_events')
    op.drop_index(op.f('ix_flow_events_flow_id'), table_name='flow_events')
    op.drop_index(op.f('ix_flow_events_event_type'), table_name='flow_events')
    op.drop_index(op.f('ix_flow_events_conversation_id'), table_name='flow_events')
    op.drop_table('flow_events')
    op.drop_index(op.f('ix_conversation_logs_tenant_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_conversation_id'), table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_flow_edges_flow_id'), table_name='flow_edges')
    op.drop_table('flow_edges')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pipeline_stages_tenant_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_base_tenant_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_flow_steps_flow_id'), table_name='flow_steps')
    op.drop_table('flow_steps')
    op.drop_index(op.f('ix_flow_nodes_tenant_id'), table_name='flow_nodes')
    op.drop_index(op.f('ix_flow_nodes_flow_id'), table_name='flow_nodes')
    op.drop_table('flow_nodes')
    op.drop_index(op.f('ix_failed_messages_tenant_id'), table_name='failed_messages')
    op.drop_index(op.f('ix_failed_messages_job_id'), table_name='failed_messages')
    op.drop_table('failed_messages')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_bot_rules_tenant_id'), table_name='bot_rules')
    op.drop_table('bot_rules')
    op.drop_index(op.f('ix_ai_config_tenant_id'), table_name='ai_config')
    op.drop_index(op.f('ix_ai_config_id'), table_name='ai_config')
    op.drop_table('ai_config')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_phone_number_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_processed_messages_tenant_id'), table_name='processed_messages')
    op.drop_table('processed_messages')
    op.drop_index(op.f('ix_flows_trigger_type'), table_name='flows')
    op.drop_index(op.f('ix_flows_tenant_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_published_version_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_current_version_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_flow_versions_flow_id'), table_name='flow_versions')
    op.drop_table('flow_versions')
    op.drop_index(op.f('ix_flow_sessions_flow_id'), table_name='flow_sessions')
    op.drop_index(op.f('ix_flow_sessions_conversation_id'), table_name='flow_sessions')
    op.drop_table('flow_sessions')
    # ### end Alembic commands ###
