"""persist marketplace installations"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "e8f1a2b3c4d5"; down_revision = "d1756d686872"; branch_labels = None; depends_on = None
def upgrade():
    op.create_table("marketplace_installations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False), sa.Column("template_id", sa.String(120), nullable=False), sa.Column("template_slug", sa.String(120), nullable=False), sa.Column("template_type", sa.String(40), nullable=False), sa.Column("template_version", sa.String(32), nullable=False), sa.Column("automation_level", sa.String(32), nullable=False), sa.Column("variant", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("idempotency_key", sa.String(255), nullable=False), sa.Column("installed_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant_users.id", ondelete="RESTRICT"), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("completed_at", sa.DateTime()), sa.Column("failed_at", sa.DateTime()), sa.Column("error_code", sa.String(80)), sa.Column("error_summary", sa.Text()), sa.Column("created_resources", postgresql.JSONB(), nullable=False), sa.Column("dependency_snapshot", postgresql.JSONB(), nullable=False), sa.Column("manifest_snapshot", postgresql.JSONB(), nullable=False), sa.Column("customization_state", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_marketplace_installation_tenant_key"))
    for name, cols in (("ix_marketplace_installations_tenant_id", ["tenant_id"]), ("ix_marketplace_installations_template_slug", ["template_slug"]), ("ix_marketplace_installations_status", ["status"]), ("ix_marketplace_installations_tenant_slug", ["tenant_id", "template_slug"]), ("ix_marketplace_installations_tenant_status", ["tenant_id", "status"])): op.create_index(name, "marketplace_installations", cols)
    op.create_table("marketplace_installation_resources", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("marketplace_installations.id", ondelete="CASCADE"), nullable=False), sa.Column("resource_type", sa.String(48), nullable=False), sa.Column("resource_id", sa.String(120), nullable=False), sa.Column("resource_name", sa.String(200), nullable=False), sa.Column("creation_status", sa.String(32), nullable=False), sa.Column("rollback_status", sa.String(32), nullable=False), sa.Column("metadata", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("installation_id", "resource_type", "resource_id", name="uq_marketplace_installation_resource"))
    op.create_index("ix_marketplace_installation_resources_installation_id", "marketplace_installation_resources", ["installation_id"])
def downgrade():
    op.drop_table("marketplace_installation_resources"); op.drop_table("marketplace_installations")
