from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.flow import FlowVersion

logger = logging.getLogger(__name__)


class FlowV2SnapshotError(RuntimeError):
    pass


@dataclass(frozen=True)
class FlowV2Snapshot:
    flow_version_id: UUID
    tenant_id: UUID
    hash: str
    nodes: tuple[dict[str, Any], ...]
    edges: tuple[dict[str, Any], ...]
    start_node_id: str
    snapshot_schema_version: int = 1
    transitions: tuple[dict[str, Any], ...] = ()

    @property
    def node_by_id(self) -> dict[str, dict[str, Any]]:
        return {str(node["id"]): node for node in self.nodes}


NORMALIZED_DEFAULT_HANDLES = {None, "", "default"}


def canonical_hash(value: dict[str, Any]) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def build_transitions_from_edges(edges: list[dict[str, Any]] | tuple[dict[str, Any], ...]) -> list[dict[str, Any]]:
    """Convert React Flow edges into explicit Runtime V2 transitions.

    React Flow stores routing in edges (`source`, `target`, `sourceHandle`).
    Runtime V2 resolves transitions from an explicit transition table embedded in
    the immutable snapshot.  Handles generated by the builder as `default` are
    semantically equivalent to an empty React Flow handle for linear nodes.
    """

    transitions: list[dict[str, Any]] = []
    for index, edge in enumerate(edges):
        if not isinstance(edge, dict):
            continue
        source = edge.get("source") or edge.get("from") or edge.get("source_node_id")
        target = edge.get("target") or edge.get("to") or edge.get("target_node_id")
        if source in (None, "") or target in (None, ""):
            continue
        source_handle = _edge_source_handle(edge)
        transition: dict[str, Any] = {
            "id": str(edge.get("id") or f"transition-{index}"),
            "source_node_id": str(source),
            "target_node_id": str(target),
            "source_handle": _runtime_source_handle(source_handle),
            "edge_id": str(edge.get("id")) if edge.get("id") is not None else None,
        }
        transitions.append({key: value for key, value in transition.items() if value is not None})
    return transitions


def normalize_source_handle(source_handle: Any) -> str | None:
    if source_handle is None:
        return None
    normalized = str(source_handle).strip()
    return None if normalized == "" else normalized


def is_default_source_handle(source_handle: Any) -> bool:
    return normalize_source_handle(source_handle) in NORMALIZED_DEFAULT_HANDLES


def _edge_source_handle(edge: dict[str, Any]) -> Any:
    data = edge.get("data") if isinstance(edge.get("data"), dict) else {}
    for key in ("sourceHandle", "source_handle"):
        if edge.get(key) is not None:
            return edge.get(key)
    for key in ("sourceHandle", "source_handle"):
        if data.get(key) is not None:
            return data.get(key)
    return None


def _runtime_source_handle(source_handle: Any) -> str | None:
    return normalize_source_handle(source_handle)


class FlowV2SnapshotRepository:
    """Loads immutable runtime snapshots exclusively from flow_versions."""

    def load(self, db: Session, *, tenant_id: UUID, flow_version_id: UUID) -> FlowV2Snapshot:
        version = db.execute(
            select(FlowVersion).where(
                FlowVersion.id == flow_version_id,
                FlowVersion.tenant_id == tenant_id,
                FlowVersion.is_published.is_(True),
            )
        ).scalar_one_or_none()
        if version is None:
            raise FlowV2SnapshotError("Published flow version not found for Runtime V2")

        stored_snapshot = version.snapshot
        if not isinstance(stored_snapshot, dict):
            raise FlowV2SnapshotError("Runtime V2 requires flow_versions.snapshot")

        expected_hash = getattr(version, "v2_snapshot_hash", None)
        if not expected_hash:
            raise FlowV2SnapshotError("Runtime V2 requires an immutable snapshot hash")

        snapshot = migrate_snapshot(stored_snapshot)
        stored_schema_version = getattr(version, "v2_snapshot_schema_version", None)
        snapshot_schema_version = int(snapshot.get("snapshot_schema_version") or snapshot.get("schema_version") or 1)
        if stored_schema_version is not None and int(stored_schema_version) != snapshot_schema_version:
            raise FlowV2SnapshotError("Flow version snapshot schema version mismatch")

        embedded_hash = stored_snapshot.get("hash")
        if embedded_hash and embedded_hash != expected_hash:
            raise FlowV2SnapshotError("Flow version embedded snapshot hash mismatch")
        hash_candidates = {
            canonical_hash({k: v for k, v in stored_snapshot.items() if k != "hash"}),
            canonical_hash({k: v for k, v in snapshot.items() if k != "hash"}),
        }
        if expected_hash not in hash_candidates:
            raise FlowV2SnapshotError("Flow version snapshot hash mismatch")

        nodes = snapshot.get("nodes")
        edges = snapshot.get("edges")
        transitions = snapshot.get("transitions")
        if not isinstance(nodes, list) or not isinstance(edges, list):
            raise FlowV2SnapshotError("Runtime V2 snapshot must contain nodes and edges arrays")
        if not isinstance(transitions, list):
            raise FlowV2SnapshotError("Runtime V2 snapshot must contain transitions array")

        start_node_id = snapshot.get("start_node_id")
        if not start_node_id:
            raise FlowV2SnapshotError("Runtime V2 snapshot must declare start_node_id")

        logger.info(
            "[V2 SNAPSHOT] loaded flow_version_id=%s tenant_id=%s start_node_id=%s nodes_count=%s edges_count=%s transitions_count=%s hash=%s",
            version.id,
            tenant_id,
            start_node_id,
            len(nodes),
            len(edges),
            len(transitions),
            expected_hash,
        )
        logger.info(
            "[V2 TRANSITIONS] loaded flow_version_id=%s transitions=%s edges=%s",
            version.id,
            transitions,
            edges,
        )

        return FlowV2Snapshot(
            flow_version_id=version.id,
            tenant_id=tenant_id,
            hash=expected_hash,
            nodes=tuple(dict(node) for node in nodes),
            edges=tuple(dict(edge) for edge in edges),
            transitions=tuple(dict(transition) for transition in transitions),
            start_node_id=str(start_node_id),
            snapshot_schema_version=snapshot_schema_version,
        )


def migrate_snapshot(snapshot: dict[str, Any]) -> dict[str, Any]:
    """Return a runtime snapshot in the current schema.

    Legacy V2 snapshots persisted only React Flow `edges`.  Runtime V2 now keeps
    explicit `transitions` derived from those edges so resolver diagnostics can
    report the exact published routing table while still reading old snapshots.
    """

    schema_version = int(snapshot.get("snapshot_schema_version") or snapshot.get("schema_version") or 1)
    if schema_version == 1:
        edges = snapshot.get("edges") if isinstance(snapshot.get("edges"), list) else []
        transitions = snapshot.get("transitions")
        if not isinstance(transitions, list):
            transitions = build_transitions_from_edges(edges)
        return {**snapshot, "snapshot_schema_version": 1, "transitions": transitions}
    raise FlowV2SnapshotError(f"Unsupported Runtime V2 snapshot_schema_version={schema_version}")
