"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, CreditCard, Loader2, RefreshCw } from "lucide-react";
import { getCurrentBilling, listBillingPlans } from "@/lib/api";
import type { BillingPlan, CurrentBillingState, EffectiveEntitlement } from "@/lib/types";

export function PlanBadge({ status }: { status?: string | null }) { const legacy = status === "legacy"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${legacy ? "bg-blue-50 text-blue-700" : "bg-emerald-50 text-emerald-700"}`}>{legacy ? "Acesso legado" : status || "Sem assinatura"}</span>; }
export function SubscriptionStatusBadge({ status }: { status?: string | null }) { return <PlanBadge status={status} />; }
export function LimitDisplay({ entitlement }: { entitlement: EffectiveEntitlement }) { return <li className="flex justify-between gap-3 text-sm text-slate-600"><span>{entitlement.feature_key.replaceAll("_", " ")}</span><span className="font-medium text-slate-900">{entitlement.limit_value === null ? "Ilimitado" : `${entitlement.limit_value} ${entitlement.limit_unit || ""}`}</span></li>; }
export function EntitlementList({ entitlements }: { entitlements: EffectiveEntitlement[] }) { return <ul className="mt-4 grid gap-2 sm:grid-cols-2">{entitlements.filter(item => item.enabled).slice(0, 12).map(item => <LimitDisplay key={item.feature_key} entitlement={item} />)}</ul>; }
export function CurrentPlanCard({ state }: { state: CurrentBillingState }) { const legacy = state.subscription?.status === "legacy"; return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Plano atual</p><h2 className="mt-1 text-xl font-bold text-slate-950">{state.plan?.name || "Sem assinatura"}</h2></div><SubscriptionStatusBadge status={state.subscription?.status} /></div><p className="mt-3 text-sm leading-6 text-slate-600">{legacy ? "Seu workspace mantém acesso integral durante a implantação dos novos planos." : state.plan?.description || "As informações do plano serão disponibilizadas em breve."}</p><button disabled className="mt-5 w-full rounded-xl bg-slate-100 px-4 py-2.5 text-sm font-semibold text-slate-500" aria-label="Upgrade disponível em breve">Upgrade <span className="font-normal">(em breve)</span></button></section>; }
export function PlanComparison({ plans }: { plans: BillingPlan[] }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-950">Comparar planos</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plans.map(plan => <div key={plan.code} className="rounded-xl border border-slate-200 p-4"><h3 className="font-semibold text-slate-900">{plan.name}</h3><p className="mt-1 text-sm text-slate-600">{plan.monthly_price_cents === null ? "Sob consulta" : `R$ ${(plan.monthly_price_cents / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}/mês`}</p><p className="mt-3 text-xs text-slate-500">{plan.features.filter(feature => feature.enabled).length} recursos configurados</p></div>)}</div></section>; }

export default function BillingTab() {
  const [state, setState] = useState<CurrentBillingState | null>(null); const [plans, setPlans] = useState<BillingPlan[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [current, catalog] = await Promise.all([getCurrentBilling(), listBillingPlans()]); setState(current); setPlans(catalog); } catch { setError("Não foi possível carregar as informações de plano. O restante do Wazza continua disponível."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <div className="flex min-h-48 items-center justify-center text-slate-500"><Loader2 className="mr-2 animate-spin" size={18} /> Carregando plano e cobrança…</div>;
  if (error) return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><p>{error}</p><button onClick={() => void load()} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-amber-300 bg-white px-3 py-2 font-semibold"><RefreshCw size={15} /> Tentar novamente</button></section>;
  if (!state?.billing_ui_enabled) return <section className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-600">A visualização de plano e cobrança não está disponível neste ambiente.</section>;
  return <div className="space-y-4"><header className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700"><CreditCard size={20} /></span><div><h1 className="text-2xl font-bold text-slate-950">Plano e cobrança</h1><p className="text-sm text-slate-600">Cobrança online ainda não está ativada.</p></div></header><CurrentPlanCard state={state} /><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-950">Recursos e limites</h2><EntitlementList entitlements={state.effective_entitlements} /></section><PlanComparison plans={plans} /><p className="flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 size={14} className="text-emerald-600" /> Nenhum recurso é bloqueado nesta fase.</p></div>;
}
