"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, CreditCard, Loader2, RefreshCw } from "lucide-react";
import { createBillingCheckout, getCurrentBilling, listBillingPlans, openBillingPortal } from "@/lib/api";
import type { BillingPlan, CurrentBillingState, EffectiveEntitlement } from "@/lib/types";

export function PlanBadge({ status }: { status?: string | null }) { const legacy = status === "legacy"; const trial = status === "trialing"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${legacy ? "bg-blue-50 text-blue-700" : trial ? "bg-violet-50 text-violet-700" : "bg-emerald-50 text-emerald-700"}`}>{legacy ? "Acesso legado" : trial ? "Trial" : status || "Sem assinatura"}</span>; }
export function SubscriptionStatusBadge({ status }: { status?: string | null }) { return <PlanBadge status={status} />; }
export function LimitDisplay({ entitlement }: { entitlement: EffectiveEntitlement }) { return <li className="flex justify-between gap-3 text-sm text-slate-600"><span>{entitlement.feature_key.replaceAll("_", " ")}</span><span className="font-medium text-slate-900">{entitlement.limit_value === null ? "Ilimitado" : `${entitlement.limit_value} ${entitlement.limit_unit || ""}`}</span></li>; }
export function EntitlementList({ entitlements }: { entitlements: EffectiveEntitlement[] }) { return <ul className="mt-4 grid gap-2 sm:grid-cols-2">{entitlements.filter(item => item.enabled).slice(0, 12).map(item => <LimitDisplay key={item.feature_key} entitlement={item} />)}</ul>; }
export function CurrentPlanCard({ state, portal }: { state: CurrentBillingState; portal: () => void }) { const legacy = state.subscription?.status === "legacy"; const trial = state.trial; return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Plano atual</p><h2 className="mt-1 text-xl font-bold text-slate-950">{trial ? "Trial Growth" : state.plan?.name || "Sem assinatura"}</h2></div><SubscriptionStatusBadge status={state.subscription?.status} /></div>{trial && <p className="mt-4 rounded-xl border border-violet-200 bg-violet-50 p-3 text-sm text-violet-900">Trial de 14 dias · {state.days_remaining} dias restantes.</p>}<p className="mt-3 text-sm leading-6 text-slate-600">{legacy ? "Seu workspace mantém acesso integral até uma assinatura Stripe ser confirmada." : state.plan?.description || "Aguardando informações da assinatura."}</p>{state.subscription?.provider === "stripe" && <button onClick={portal} className="mt-5 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Gerenciar cobrança</button>}</section>; }
export function PlanComparison({ plans, enabled, checkout }: { plans: BillingPlan[]; enabled: boolean; checkout: (code: string, interval: "monthly" | "annual") => void }) { const [interval, setInterval] = useState<"monthly" | "annual">("monthly"); return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold text-slate-950">Comparar planos</h2><div className="rounded-lg bg-slate-100 p-1" aria-label="Periodicidade"><button onClick={() => setInterval("monthly")} className={`rounded px-3 py-1 text-sm ${interval === "monthly" ? "bg-white shadow" : ""}`}>Mensal</button><button onClick={() => setInterval("annual")} className={`rounded px-3 py-1 text-sm ${interval === "annual" ? "bg-white shadow" : ""}`}>Anual</button></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plans.map(plan => { const amount = interval === "monthly" ? plan.monthly_price_cents : plan.annual_price_cents; return <div key={plan.code} className="rounded-xl border border-slate-200 p-4"><h3 className="font-semibold text-slate-900">{plan.name}</h3><p className="mt-1 text-sm text-slate-600">{amount === null ? "Sob consulta" : `R$ ${(amount / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}/${interval === "monthly" ? "mês" : "ano"}`}</p><button disabled={!enabled || amount === null} onClick={() => checkout(plan.code, interval)} className="mt-4 rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40">Assinar</button></div>; })}</div></section>; }

export default function BillingTab() {
  const [state, setState] = useState<CurrentBillingState | null>(null); const [plans, setPlans] = useState<BillingPlan[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [current, catalog] = await Promise.all([getCurrentBilling(), listBillingPlans()]); setState(current); setPlans(catalog); } catch { setError("Não foi possível carregar as informações de plano. O restante do Wazza continua disponível."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <div className="flex min-h-48 items-center justify-center text-slate-500"><Loader2 className="mr-2 animate-spin" size={18} /> Carregando plano e cobrança…</div>;
  if (error) return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><p>{error}</p><button onClick={() => void load()} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-amber-300 bg-white px-3 py-2 font-semibold"><RefreshCw size={15} /> Tentar novamente</button></section>;
  if (!state?.billing_ui_enabled) return <section className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-600">A visualização de plano e cobrança não está disponível neste ambiente.</section>;
  const checkout = async (code: string, interval: "monthly" | "annual") => { setBusy(true); try { const result = await createBillingCheckout(code, interval); window.location.assign(result.checkout_url); } catch { setError("Não foi possível iniciar o Checkout."); } finally { setBusy(false); } };
  const portal = async () => { setBusy(true); try { const result = await openBillingPortal(); window.location.assign(result.portal_url); } catch { setError("Não foi possível abrir o portal de cobrança."); } finally { setBusy(false); } };
  const pending = new URLSearchParams(typeof window === "undefined" ? "" : window.location.search).get("checkout") === "success";
  return <div className="space-y-4"><header className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700"><CreditCard size={20} /></span><div><h1 className="text-2xl font-bold text-slate-950">Plano e cobrança</h1><p className="text-sm text-slate-600">{state.stripe_enabled ? "Escolha um plano ou gerencie sua assinatura." : "Cobrança online temporariamente indisponível."}</p></div></header>{pending && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900">Pagamento recebido. Estamos confirmando sua assinatura.</p>}{busy && <p className="text-sm text-slate-500">Redirecionando para a cobrança segura…</p>}<CurrentPlanCard state={state} portal={() => void portal()} /><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-950">Recursos e limites</h2><EntitlementList entitlements={state.effective_entitlements} /></section><PlanComparison plans={plans} enabled={Boolean(state.stripe_enabled)} checkout={(code, interval) => void checkout(code, interval)} /><p className="flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 size={14} className="text-emerald-600" /> Nenhum recurso é bloqueado nesta fase.</p></div>;
}
