'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Download, RefreshCw, Search } from 'lucide-react';
import { campaignAnalyticsExportUrl, getCampaignAnalyticsByCampaign, getCampaignAnalyticsByTemplate, getCampaignAnalyticsFailures, getCampaignAnalyticsHeatmap, getCampaignAnalyticsSummary, getCampaignAnalyticsTimeline, listTemplates, listWhatsAppCampaigns, listWhatsAppProviders, CampaignAnalyticsPage, CampaignAnalyticsSummary, FailureAnalyticsRow, HeatmapAnalytics, TemplateAnalyticsRow, TimelineAnalytics } from '@/lib/api';
import { WhatsAppCampaign, WhatsAppProvider, WhatsAppTemplate } from '@/lib/types';
import CampaignDetailsDrawer from '../campaigns/CampaignDetailsDrawer';
import CampaignStatusBadge from '../campaigns/CampaignStatusBadge';
import { formatCompact, formatDateTime, formatDuration, formatInteger, formatPercent } from './formatters';
import type { CampaignReportPreviewScenario } from './previewFixtures';

const iso = (d: Date) => d.toISOString();
const defaultStart = (days = 30) => { const d = new Date(); d.setDate(d.getDate() - days); return d; };
const rate = (a?: number | null, b?: number | null) => b ? (Number(a || 0) / b) * 100 : null;
const previewAllowed = process.env.NODE_ENV !== 'production';
const colors = { sent: '#64748b', delivered: '#059669', read: '#4f46e5', failed: '#dc2626' };

function EmptyState({ text }: { text: string }) { return <p className="rounded-2xl bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">{text}</p>; }
function MetricCard({ label, value, tone = 'neutral', hint, primary }: { label: string; value?: number | string | null; tone?: 'neutral'|'success'|'read'|'danger'|'warn'; hint?: string; primary?: boolean }) {
  const toneCls = { neutral:'border-slate-200 bg-white text-slate-900', success:'border-emerald-200 bg-emerald-50/40 text-emerald-900', read:'border-indigo-200 bg-indigo-50/50 text-indigo-900', danger:'border-rose-200 bg-rose-50/40 text-rose-900', warn:'border-amber-200 bg-amber-50/50 text-amber-900' }[tone];
  const numeric = typeof value === 'number';
  return <article title={hint || (numeric ? formatInteger(value) : undefined)} className={`rounded-[1.35rem] border p-4 shadow-[0_18px_50px_-42px_rgba(15,23,42,.55)] ${toneCls} ${primary ? 'md:col-span-2' : ''}`}><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-slate-500">{label}</p><p className={`${primary ? 'text-3xl lg:text-4xl' : 'text-2xl'} mt-2 truncate font-semibold tabular-nums`}>{numeric ? formatCompact(value) : value ?? '—'}</p></article>;
}

export default function CampaignReportsPage(){
  const [period,setPeriod]=useState('30'); const [start,setStart]=useState(iso(defaultStart())); const [end,setEnd]=useState(iso(new Date()));
  const [filters,setFilters]=useState({ campaign_id:'', template_id:'', provider_id:'', status:'', template_category:'', template_language:'', search:'' });
  const [summary,setSummary]=useState<CampaignAnalyticsSummary|null>(null); const [campaigns,setCampaigns]=useState<CampaignAnalyticsPage|null>(null); const [templates,setTemplates]=useState<TemplateAnalyticsRow[]>([]); const [timeline,setTimeline]=useState<TimelineAnalytics|null>(null); const [failures,setFailures]=useState<FailureAnalyticsRow[]>([]); const [heatmap,setHeatmap]=useState<HeatmapAnalytics|null>(null);
  const [allCampaigns,setAllCampaigns]=useState<WhatsAppCampaign[]>([]); const [allTemplates,setAllTemplates]=useState<WhatsAppTemplate[]>([]); const [providers,setProviders]=useState<WhatsAppProvider[]>([]);
  const [selected,setSelected]=useState<WhatsAppCampaign|null>(null); const [compare,setCompare]=useState<string[]>([]); const [metric,setMetric]=useState('total_delivered'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [updated,setUpdated]=useState<Date|null>(null); const [preview,setPreview]=useState<CampaignReportPreviewScenario | ''>('');
  const params = useMemo(()=>({ start, end, ...filters }),[start,end,filters]);
  const applyPreview = useCallback(async (scenario: CampaignReportPreviewScenario) => { if (!previewAllowed) return; const { buildCampaignReportPreview } = await import('./previewFixtures'); const data = buildCampaignReportPreview(scenario); setSummary(data.summary); setCampaigns(data.campaigns); setTemplates(data.templates); setTimeline(data.timeline); setFailures(data.failures); setHeatmap(data.heatmap); setUpdated(new Date()); setLoading(false); }, []);
  const reload = useCallback(async()=>{ if (previewAllowed && preview) { await applyPreview(preview); return; } setLoading(true); setError(''); try { const [s,c,t,l,f,h] = await Promise.all([getCampaignAnalyticsSummary(params),getCampaignAnalyticsByCampaign({...params, page_size:20}),getCampaignAnalyticsByTemplate(params),getCampaignAnalyticsTimeline(params),getCampaignAnalyticsFailures(params),getCampaignAnalyticsHeatmap({...params, metric:'read'})]); setSummary(s); setCampaigns(c); setTemplates(t); setTimeline(l); setFailures(f); setHeatmap(h); setUpdated(new Date()); } catch(e:any){ setError(e?.message || 'Falha ao carregar relatórios'); } finally { setLoading(false); } },[params, preview, applyPreview]);
  useEffect(()=>{ void Promise.all([listWhatsAppCampaigns(), listTemplates(), listWhatsAppProviders()]).then(([c,t,p])=>{setAllCampaigns(c); setAllTemplates(t); setProviders(p);}); },[]);
  useEffect(()=>{ void reload(); },[reload]);
  function quick(v:string){ setPeriod(v); const now=new Date(); const s=new Date(now); if(v==='today') s.setHours(0,0,0,0); else if(v==='yesterday'){ s.setDate(s.getDate()-1); s.setHours(0,0,0,0); now.setDate(now.getDate()-1); now.setHours(23,59,59,999); } else s.setDate(s.getDate()-Number(v)); setStart(iso(s)); setEnd(iso(now)); }
  const compared=(campaigns?.items||[]).filter(c=>compare.includes(c.id));
  const timelineData = useMemo(() => timeline?.items || [], [timeline]);
  const maxFailure = Math.max(...failures.map(f=>f.count), 1); const maxRead = Math.max(...templates.map(t=>t.read_rate || 0), 1); const maxHeat = Math.max(...(heatmap?.items || []).map(h=>h.count), 1);
  const funnel = [['Destinatários', summary?.total_recipients], ['Enviadas', summary?.total_sent], ['Entregues', summary?.total_delivered], ['Lidas', summary?.total_read]] as const;
  return <div className="min-h-screen bg-slate-50 px-4 py-5 text-slate-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="rounded-[1.75rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h1 className="text-2xl font-semibold">Relatórios de campanhas</h1><p className="mt-1 text-sm text-slate-500">Visualização premium de entregas, leituras, falhas, templates e comparação operacional.</p></div><div className="flex shrink-0 gap-2"><button onClick={()=>void reload()} className="secondary-button inline-flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button><a className="primary-button inline-flex items-center gap-2" href={campaignAnalyticsExportUrl({...params,type:'campaigns'})}><Download size={14}/>Exportar CSV</a></div></div>
      <div className="mt-4 grid gap-3"><div className="flex flex-wrap gap-2">{[['Hoje','today'],['Ontem','yesterday'],['7 dias','7'],['30 dias','30'],['90 dias','90']].map(([l,v])=><button key={v} onClick={()=>quick(v)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${period===v?'border-emerald-300 bg-emerald-50 text-emerald-700':'border-slate-200 text-slate-600'}`}>{l}</button>)}<button onClick={()=>setPeriod('custom')} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">Personalizado</button></div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-8"><input aria-label="Início" type="datetime-local" className="input" value={start.slice(0,16)} onChange={e=>setStart(new Date(e.target.value).toISOString())}/><input aria-label="Fim" type="datetime-local" className="input" value={end.slice(0,16)} onChange={e=>setEnd(new Date(e.target.value).toISOString())}/><select aria-label="Remetente" className="input" value={filters.provider_id} onChange={e=>setFilters({...filters,provider_id:e.target.value})}><option value="">Remetente</option>{providers.map(p=><option key={p.id} value={p.id}>{p.display_name||p.phone_number_id||p.id}</option>)}</select><select aria-label="Status" className="input" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Status</option>{['draft','scheduled','running','paused','completed','cancelled','failed'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Campanha" className="input xl:col-span-2" value={filters.campaign_id} onChange={e=>setFilters({...filters,campaign_id:e.target.value})}><option value="">Todas as campanhas</option>{allCampaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Template" className="input" value={filters.template_id} onChange={e=>setFilters({...filters,template_id:e.target.value})}><option value="">Templates</option>{allTemplates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="secondary-button" onClick={()=>setFilters({ campaign_id:'', template_id:'', provider_id:'', status:'', template_category:'', template_language:'', search:'' })}>Limpar</button></div></div>
      {previewAllowed && <div className="mt-3 flex flex-wrap items-center gap-2 rounded-2xl bg-amber-50 px-3 py-2 text-xs text-amber-800"><span className="font-semibold">Preview dev/test:</span>{(['low','medium','high','extreme'] as CampaignReportPreviewScenario[]).map(s=><button key={s} onClick={()=>setPreview(s)} className={`rounded-full px-2.5 py-1 ${preview===s?'bg-amber-200':'bg-white'}`}>{s}</button>)}<button onClick={()=>setPreview('')} className="underline">dados reais</button></div>}
    </header>
    {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error} <button onClick={()=>void reload()} className="underline">Tentar novamente</button></div>}
    <section className="grid gap-3 md:grid-cols-4 xl:grid-cols-8"><MetricCard primary label="Enviadas" value={summary?.total_sent} tone="neutral"/><MetricCard primary label="Entregues" value={summary?.total_delivered} tone="success"/><MetricCard primary label="Lidas" value={summary?.total_read} tone="read"/><MetricCard primary label="Falhas" value={summary?.total_failed} tone="danger"/><MetricCard label="Campanhas criadas" value={summary?.campaigns_created}/><MetricCard label="Concluídas" value={summary?.campaigns_completed}/><MetricCard label="Destinatários" value={summary?.total_recipients}/><MetricCard label="Taxa entrega" value={formatPercent(summary?.delivery_rate)} hint="total_delivered / total_sent × 100"/><MetricCard label="Taxa leitura" value={formatPercent(summary?.read_rate)} hint="total_read / total_delivered × 100"/><MetricCard label="Taxa falha" value={formatPercent(summary?.failure_rate)} tone="warn" hint="total_failed / total_recipients × 100"/></section>
    <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><h2 className="font-semibold">Funil de desempenho</h2>{funnel.map(([label,val],i)=>{ const prev = i ? funnel[i-1][1] : val; const loss = i ? Number(prev || 0) - Number(val || 0) : 0; return <div key={label} className="mt-4"><div className="flex items-end justify-between gap-3 text-sm"><div><p className="font-medium">{label}</p>{i>0&&<p className="text-xs text-slate-500">Perda: {formatInteger(Math.max(loss,0))}</p>}</div><p className="font-semibold tabular-nums">{formatInteger(val)} {i>0&&<span className="text-slate-500">— {formatPercent(rate(val, prev))}</span>}</p></div><div className="mt-2 h-2.5 rounded-full bg-slate-100"><div className="h-2.5 rounded-full bg-slate-700" style={{width:`${Math.max(2, Math.min(rate(val, summary?.total_recipients) || 0, 100))}%`}} /></div></div>})}</div><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><h2 className="font-semibold">Evolução temporal</h2><ResponsiveContainer width="100%" height={300}><LineChart data={timelineData} margin={{ top: 16, right: 20, bottom: 0, left: 0 }}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3"/><XAxis dataKey="bucket" minTickGap={34} tickFormatter={v=>new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}/><YAxis tickFormatter={formatCompact} width={58}/><Tooltip labelFormatter={v=>formatDateTime(String(v))} formatter={(v:any,n)=>[formatInteger(Number(v)), n]}/><Legend /><Line dot={timelineData.length<16} activeDot strokeWidth={2} type="monotone" dataKey="sent" name="Enviadas" stroke={colors.sent}/><Line dot={timelineData.length<16} type="monotone" dataKey="delivered" name="Entregues" stroke={colors.delivered}/><Line dot={timelineData.length<16} type="monotone" dataKey="read" name="Lidas" stroke={colors.read}/><Line dot={timelineData.length<16} type="monotone" dataKey="failed" name="Falhas" stroke={colors.failed}/></LineChart></ResponsiveContainer></div></section>
    <section className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Desempenho por campanha</h2><label className="relative"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input className="input pl-9" placeholder="Buscar campanha" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label></div><div className="max-h-[560px] overflow-auto rounded-2xl border border-slate-100"><table className="w-full min-w-[1180px] text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-left text-[11px] uppercase tracking-[.12em] text-slate-500"><tr>{['Comparar','Campanha','Status','Template','Audiência','Enviadas','Entregues','Lidas','Falhas','Entrega','Leitura','Início','Duração'].map((h,i)=><th className={`p-3 ${i===1?'sticky left-0 bg-slate-50':''} ${i>3&&i<11?'text-right':''}`} key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{campaigns?.items.map(c=><tr key={c.id} className="hover:bg-slate-50/80"><td className="p-3"><input aria-label={`Comparar ${c.name}`} type="checkbox" checked={compare.includes(c.id)} disabled={!compare.includes(c.id)&&compare.length>=5} onChange={e=>setCompare(e.target.checked?[...compare,c.id]:compare.filter(id=>id!==c.id))}/></td><td className="sticky left-0 max-w-[260px] bg-white p-3 hover:bg-slate-50"><button title={c.name} className="block truncate font-semibold text-emerald-700" onClick={()=>setSelected(c)}>{c.name}</button></td><td className="p-3"><CampaignStatusBadge status={c.status}/></td><td title={c.template_name||c.template_id} className="max-w-[210px] truncate p-3">{c.template_name||c.template_id}</td>{[c.total_recipients,c.total_sent,c.total_delivered,c.total_read,c.total_failed].map((v,i)=><td key={i} className="p-3 text-right tabular-nums">{formatInteger(v)}</td>)}<td className="p-3 text-right">{formatPercent(c.delivery_rate)}</td><td className="p-3 text-right">{formatPercent(c.read_rate)}</td><td className="p-3">{formatDateTime(c.started_at)}</td><td className="p-3">{formatDuration(c.duration_seconds)}</td></tr>)}</tbody></table></div>{!loading&&!campaigns?.items.length&&<EmptyState text="Sem dados no período."/>}</section>
    <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><h2 className="font-semibold">Ranking por template</h2>{templates.length?templates.map((t,i)=><div key={t.template_id} className="mt-3 rounded-2xl bg-slate-50 p-3"><div className="flex gap-3"><span className="text-sm font-bold text-slate-400">#{i+1}</span><div className="min-w-0 flex-1"><p title={t.template_name} className="truncate font-semibold">{t.template_name}</p><p className="text-xs text-slate-500">{t.category||'—'} · {t.language||'—'} · {t.campaigns} campanhas {t.total_sent<1000?'· Amostra pequena':''}</p><p className="mt-1 text-xs text-slate-600">{formatInteger(t.total_sent)} enviadas · {formatInteger(t.total_delivered)} entregues · {formatInteger(t.total_read)} lidas · {formatInteger(t.total_failed)} falhas</p><div className="mt-2 h-2 rounded-full bg-white"><div className="h-2 rounded-full bg-indigo-500" style={{width:`${Math.max(2, ((t.read_rate||0)/maxRead)*100)}%`}}/></div></div><span className="font-semibold text-indigo-700">{formatPercent(t.read_rate)}</span></div></div>):<EmptyState text="Sem templates suficientes."/>}</div><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><h2 className="font-semibold">Análise de falhas</h2>{failures.length?[...failures].sort((a,b)=>b.count-a.count).map(f=><details key={f.category} className="mt-3 rounded-2xl bg-slate-50 p-3"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{f.category}</p><p className="text-sm text-slate-600">{formatInteger(f.count)} · {formatPercent(f.percent)}</p></div><span className="h-2 w-28 rounded-full bg-slate-200"><span className="block h-2 rounded-full bg-rose-500" style={{width:`${(f.count/maxFailure)*100}%`}}/></span></div><p className="mt-2 text-sm text-slate-600">{f.recommendation}</p></summary><p className="mt-2 text-xs text-slate-500">Códigos técnicos: {f.codes.join(', ')}</p></details>):<EmptyState text="Nenhuma falha relevante no período."/>}</div></section>
    <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><h2 className="font-semibold">Distribuição por horário</h2><p className="text-xs text-slate-500">Timezone do tenant visível no backend; valores por dia da semana e hora.</p>{heatmap?.sufficient_data?<div className="mt-4 overflow-x-auto"><div className="grid min-w-[760px] grid-cols-[72px_repeat(24,1fr)] gap-1 text-[10px]"><span/>{Array.from({length:24},(_,h)=><span key={h} className="text-center text-slate-400">{h}</span>)}{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((d,wd)=><div key={d} className="contents"><span className="py-1 text-slate-500">{d}</span>{Array.from({length:24},(_,h)=>{ const cell=heatmap.items.find(x=>x.weekday===wd&&x.hour===h); const opacity=Math.max(.08,(cell?.count||0)/maxHeat); return <span key={`${wd}-${h}`} title={`${d}, ${h}h: ${formatInteger(cell?.count||0)}`} className="h-6 rounded" style={{backgroundColor:`rgba(16, 185, 129, ${opacity})`}}/>})}</div>)}</div><p className="mt-2 text-xs text-slate-500">Legenda: intensidade maior indica mais leituras.</p></div>:<EmptyState text="Dados insuficientes para exibir distribuição por horário."/>}</div><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Comparação entre campanhas</h2><select className="input max-w-[220px]" value={metric} onChange={e=>setMetric(e.target.value)}>{[['total_recipients','Audiência'],['total_sent','Enviadas'],['total_delivered','Entregues'],['total_read','Lidas'],['total_failed','Falhas'],['delivery_rate','Taxa entrega'],['read_rate','Taxa leitura']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{compared.length>=2?<><ResponsiveContainer width="100%" height={240}><BarChart data={compared}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3"/><XAxis dataKey="name" hide/><YAxis tickFormatter={formatCompact}/><Tooltip formatter={(v:any)=> metric.includes('rate') ? formatPercent(Number(v)) : formatInteger(Number(v))}/><Bar dataKey={metric} fill="#4f46e5" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer><div className="overflow-x-auto"><table className="mt-2 w-full min-w-[560px] text-xs"><tbody>{compared.map(c=><tr key={c.id} className="border-t"><td className="max-w-[220px] truncate py-2 font-medium">{c.name}</td><td className="text-right">{metric.includes('rate')?formatPercent((c as any)[metric]):formatInteger((c as any)[metric])}</td></tr>)}</tbody></table></div></>:<EmptyState text="Selecione de 2 a 5 campanhas na tabela para comparar uma métrica por vez."/>}</div></section>
    <p className="text-xs text-slate-400">Última atualização: {updated?updated.toLocaleString('pt-BR'):'—'} · Página {campaigns?.page || 1} de {Math.max(1, Math.ceil((campaigns?.total || 0)/(campaigns?.page_size || 20)))} com paginação backend.</p>{selected && <CampaignDetailsDrawer campaign={selected} template={allTemplates.find(t=>t.id===selected.template_id)} onClose={()=>setSelected(null)} actions={null}/>}
  </div></div>;
}
