'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { RefreshCw, Download, Search } from 'lucide-react';
import { campaignAnalyticsExportUrl, getCampaignAnalyticsByCampaign, getCampaignAnalyticsByTemplate, getCampaignAnalyticsFailures, getCampaignAnalyticsHeatmap, getCampaignAnalyticsSummary, getCampaignAnalyticsTimeline, listTemplates, listWhatsAppCampaigns, listWhatsAppProviders, CampaignAnalyticsPage, CampaignAnalyticsSummary, FailureAnalyticsRow, HeatmapAnalytics, TemplateAnalyticsRow, TimelineAnalytics } from '@/lib/api';
import { WhatsAppCampaign, WhatsAppProvider, WhatsAppTemplate } from '@/lib/types';
import CampaignStatusBadge from '../campaigns/CampaignStatusBadge';
import CampaignDetailsDrawer from '../campaigns/CampaignDetailsDrawer';

const fmt = new Intl.NumberFormat('pt-BR');
const pct = (v?: number | null) => v === null || v === undefined ? '—' : `${v.toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`;
const iso = (d: Date) => d.toISOString();
function defaultStart(days=30){ const d = new Date(); d.setDate(d.getDate()-days); return d; }
function maskPhone(v?: string){ return v ? v.replace(/\d(?=\d{4})/g, '•') : '—'; }

export default function CampaignReportsPage(){
  const [period,setPeriod]=useState('30'); const [start,setStart]=useState(iso(defaultStart())); const [end,setEnd]=useState(iso(new Date()));
  const [filters,setFilters]=useState({ campaign_id:'', template_id:'', provider_id:'', status:'', template_category:'', template_language:'', search:'' });
  const [summary,setSummary]=useState<CampaignAnalyticsSummary|null>(null); const [campaigns,setCampaigns]=useState<CampaignAnalyticsPage|null>(null); const [templates,setTemplates]=useState<TemplateAnalyticsRow[]>([]); const [timeline,setTimeline]=useState<TimelineAnalytics|null>(null); const [failures,setFailures]=useState<FailureAnalyticsRow[]>([]); const [heatmap,setHeatmap]=useState<HeatmapAnalytics|null>(null);
  const [allCampaigns,setAllCampaigns]=useState<WhatsAppCampaign[]>([]); const [allTemplates,setAllTemplates]=useState<WhatsAppTemplate[]>([]); const [providers,setProviders]=useState<WhatsAppProvider[]>([]);
  const [selected,setSelected]=useState<WhatsAppCampaign|null>(null); const [compare,setCompare]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [updated,setUpdated]=useState<Date|null>(null);
  const params = useMemo(()=>({ start, end, ...filters }),[start,end,filters]);
  const reload = useCallback(async()=>{ setLoading(true); setError(''); try { const [s,c,t,l,f,h] = await Promise.all([getCampaignAnalyticsSummary(params),getCampaignAnalyticsByCampaign({...params, page_size:20}),getCampaignAnalyticsByTemplate(params),getCampaignAnalyticsTimeline(params),getCampaignAnalyticsFailures(params),getCampaignAnalyticsHeatmap({...params, metric:'read'})]); setSummary(s); setCampaigns(c); setTemplates(t); setTimeline(l); setFailures(f); setHeatmap(h); setUpdated(new Date()); } catch(e:any){ setError(e?.message || 'Falha ao carregar relatórios'); } finally { setLoading(false); } },[params]);
  useEffect(()=>{ void Promise.all([listWhatsAppCampaigns(), listTemplates(), listWhatsAppProviders()]).then(([c,t,p])=>{setAllCampaigns(c); setAllTemplates(t); setProviders(p);}); },[]);
  useEffect(()=>{ void reload(); },[reload]);
  useEffect(()=>{ const id=setInterval(()=>{ if(!document.hidden) void reload(); },60000); return()=>clearInterval(id); },[reload]);
  function quick(v:string){ setPeriod(v); const now=new Date(); const s=new Date(now); if(v==='today') s.setHours(0,0,0,0); else if(v==='yesterday'){ s.setDate(s.getDate()-1); s.setHours(0,0,0,0); now.setDate(now.getDate()-1); now.setHours(23,59,59,999); } else s.setDate(s.getDate()-Number(v)); setStart(iso(s)); setEnd(iso(now)); }
  const compared=(campaigns?.items||[]).filter(c=>compare.includes(c.id));
  return <div className="min-h-screen bg-slate-50 px-4 py-6 text-slate-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-semibold">Relatórios de campanhas</h1><p className="mt-1 text-sm text-slate-500">Analise entregas, leituras e falhas das campanhas de WhatsApp.</p><p className="mt-1 text-xs text-slate-400">Campanhas por created_at; eventos por sent_at, delivered_at, read_at e failed_at.</p></div><div className="flex gap-2"><button onClick={()=>void reload()} className="secondary-button inline-flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button><a className="primary-button inline-flex items-center gap-2" href={campaignAnalyticsExportUrl({...params,type:'campaigns'})}><Download size={14}/>Exportar CSV</a></div></header>
    <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-6">{[['Hoje','today'],['Ontem','yesterday'],['Últimos 7 dias','7'],['Últimos 30 dias','30'],['Últimos 90 dias','90']].map(([l,v])=><button key={v} onClick={()=>quick(v)} className={`rounded-2xl border px-3 py-2 text-sm ${period===v?'border-emerald-400 bg-emerald-50 text-emerald-700':'border-slate-200'}`}>{l}</button>)}<button onClick={()=>setPeriod('custom')} className="rounded-2xl border border-slate-200 px-3 py-2 text-sm">Personalizado</button></div><div className="mt-4 grid gap-3 md:grid-cols-4"><input type="datetime-local" className="input" value={start.slice(0,16)} onChange={e=>setStart(new Date(e.target.value).toISOString())}/><input type="datetime-local" className="input" value={end.slice(0,16)} onChange={e=>setEnd(new Date(e.target.value).toISOString())}/><select className="input" value={filters.campaign_id} onChange={e=>setFilters({...filters,campaign_id:e.target.value})}><option value="">Todas as campanhas</option>{allCampaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="input" value={filters.template_id} onChange={e=>setFilters({...filters,template_id:e.target.value})}><option value="">Todos os templates</option>{allTemplates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className="input" value={filters.provider_id} onChange={e=>setFilters({...filters,provider_id:e.target.value})}><option value="">Todos os remetentes</option>{providers.map(p=><option key={p.id} value={p.id}>{p.display_name||p.phone_number_id||p.id}</option>)}</select><select className="input" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option>{['draft','scheduled','running','paused','completed','cancelled','failed'].map(s=><option key={s}>{s}</option>)}</select><input className="input" placeholder="Buscar campanha" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><button className="secondary-button" onClick={()=>setFilters({ campaign_id:'', template_id:'', provider_id:'', status:'', template_category:'', template_language:'', search:'' })}>Limpar filtros</button></div></section>
    {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error} <button onClick={()=>void reload()} className="underline">Tentar novamente</button></div>}
    <section className="grid gap-3 md:grid-cols-5">{[['Campanhas criadas',summary?.campaigns_created],['Campanhas concluídas',summary?.campaigns_completed],['Destinatários',summary?.total_recipients],['Enviadas',summary?.total_sent],['Entregues',summary?.total_delivered],['Lidas',summary?.total_read],['Falhas',summary?.total_failed],['Taxa de entrega',pct(summary?.delivery_rate),'total_delivered / total_sent × 100'],['Taxa de leitura',pct(summary?.read_rate),'total_read / total_delivered × 100'],['Taxa de falha',pct(summary?.failure_rate),'total_failed / total_recipients × 100']].map(([k,v,title])=><div key={k as string} title={String(title||'')} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{k}</p><p className="mt-2 text-2xl font-semibold">{typeof v==='number'?fmt.format(v):v??(loading?'…':'—')}</p></div>)}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold">Funil de desempenho</h2>{['total_recipients','total_sent','total_delivered','total_read'].map((k,i,a)=>{ const labels:any={total_recipients:'Destinatários',total_sent:'Enviadas',total_delivered:'Entregues',total_read:'Lidas'}; const val=(summary as any)?.[k]||0; const prev=i?(summary as any)?.[a[i-1]]||0:val; return <div key={k} className="mt-4"><div className="flex justify-between text-sm"><span>{labels[k]}</span><span>{fmt.format(val)} — {i?pct(_rateLocal(val,prev)):'100%'}</span></div><div className="mt-2 h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-emerald-500" style={{width:`${Math.min(_rateLocal(val,(summary as any)?.total_recipients||val)||0,100)}%`}}/></div></div>})}</div><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold">Evolução temporal</h2><ResponsiveContainer width="100%" height={260}><AreaChart data={timeline?.items||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="bucket" hide/><YAxis/><Tooltip/><Area dataKey="sent" name="Enviadas" stroke="#10b981" fill="#d1fae5"/><Area dataKey="delivered" name="Entregues" stroke="#0ea5e9" fill="#e0f2fe"/><Area dataKey="read" name="Lidas" stroke="#6366f1" fill="#e0e7ff"/><Area dataKey="failed" name="Falhas" stroke="#ef4444" fill="#fee2e2"/></AreaChart></ResponsiveContainer></div></section>
    <section className="rounded-3xl border bg-white p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Desempenho por campanha</h2><Search size={16}/></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead className="text-left text-xs uppercase text-slate-400"><tr>{['Comparar','Campanha','Status','Template','Audiência','Enviadas','Entregues','Lidas','Falhas','Taxa entrega','Taxa leitura','Início','Duração'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{campaigns?.items.map(c=><tr key={c.id} className="border-t hover:bg-slate-50"><td className="p-3"><input type="checkbox" checked={compare.includes(c.id)} disabled={!compare.includes(c.id)&&compare.length>=5} onChange={e=>setCompare(e.target.checked?[...compare,c.id]:compare.filter(id=>id!==c.id))}/></td><td className="p-3"><button className="font-semibold text-emerald-700" onClick={()=>setSelected(c)}>{c.name}</button></td><td className="p-3"><CampaignStatusBadge status={c.status}/></td><td className="p-3">{c.template_name||c.template_id}</td><td className="p-3">{fmt.format(c.total_recipients)}</td><td className="p-3">{fmt.format(c.total_sent)}</td><td className="p-3">{fmt.format(c.total_delivered)}</td><td className="p-3">{fmt.format(c.total_read)}</td><td className="p-3">{fmt.format(c.total_failed)}</td><td className="p-3">{pct(c.delivery_rate)}</td><td className="p-3">{pct(c.read_rate)}</td><td className="p-3">{c.started_at?new Date(c.started_at).toLocaleString('pt-BR'):'—'}</td><td className="p-3">{c.duration_seconds?`${Math.round(c.duration_seconds/60)} min`:'—'}</td></tr>)}</tbody></table></div>{!loading&&!campaigns?.items.length&&<p className="py-8 text-center text-slate-500">Sem dados no período.</p>}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold">Desempenho por template</h2>{templates.map(t=><div key={t.template_id} className="mt-3 rounded-2xl bg-slate-50 p-3"><p className="font-semibold">{t.template_name}</p><p className="text-xs text-slate-500">{t.category||'—'} · {t.language||'—'} · {t.campaigns} campanhas</p><p className="mt-2 text-sm">{fmt.format(t.total_recipients)} destinatários · entrega {pct(t.delivery_rate)} · leitura {pct(t.read_rate)}</p></div>)}</div><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold">Análise de falhas</h2>{failures.map(f=><div key={f.category} className="mt-3 rounded-2xl bg-slate-50 p-3"><p className="font-semibold">{f.category}</p><p className="text-sm">{fmt.format(f.count)} falhas · {pct(f.percent)}</p><p className="text-xs text-slate-500">Códigos: {f.codes.join(', ')}</p><p className="mt-1 text-sm text-slate-600">{f.recommendation}</p></div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold">Distribuição por horário</h2>{heatmap?.sufficient_data?<div className="mt-4 grid grid-cols-12 gap-1">{heatmap.items.map((h,i)=><div key={i} title={`Dia ${h.weekday}, ${h.hour}h: ${h.count}`} className="h-8 rounded bg-emerald-100 text-center text-[10px] leading-8 text-emerald-900">{h.count}</div>)}</div>:<p className="mt-4 text-sm text-slate-500">Dados insuficientes para exibir distribuição por horário.</p>}</div><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold">Comparação entre campanhas</h2><ResponsiveContainer width="100%" height={220}><BarChart data={compared}><XAxis dataKey="name" hide/><YAxis/><Tooltip/><Bar dataKey="total_delivered" name="Entregues" fill="#10b981"/><Bar dataKey="total_read" name="Lidas" fill="#6366f1"/><Bar dataKey="total_failed" name="Falhas" fill="#ef4444"/></BarChart></ResponsiveContainer><p className="text-xs text-slate-500">Selecione de 2 a 5 campanhas na tabela. Destaques são apenas maiores/menores métricas, sem declarar vencedora.</p></div></section>
    <p className="text-xs text-slate-400">Última atualização: {updated?updated.toLocaleString('pt-BR'):'—'} · Telefones exibidos são mascarados quando aplicável: {maskPhone('5511999999999')}</p>
    {selected && <CampaignDetailsDrawer campaign={selected} template={allTemplates.find(t=>t.id===selected.template_id)} onClose={()=>setSelected(null)} actions={null}/>} 
  </div></div>;
}
function _rateLocal(a:number,b:number){ return b?Math.round((a/b)*1000)/10:null; }
