import type { CampaignAnalyticsPage, CampaignAnalyticsSummary, FailureAnalyticsRow, HeatmapAnalytics, TemplateAnalyticsRow, TimelineAnalytics } from '@/lib/api';

export type CampaignReportPreviewScenario = 'low' | 'medium' | 'high' | 'extreme';
const long = 'Campanha sazonal com nome extremamente longo para validar truncamento e tooltips no painel executivo Wazza';

export function buildCampaignReportPreview(scenario: CampaignReportPreviewScenario) {
  const size = scenario === 'low' ? 3 : scenario === 'medium' ? 20 : scenario === 'high' ? 120 : 24;
  const multiplier = scenario === 'low' ? 120 : scenario === 'medium' ? 2200 : scenario === 'high' ? 85000 : 9500;
  const items = Array.from({ length: size }, (_, i) => {
    const recipients = (i + 1) * multiplier;
    const sent = scenario === 'extreme' && i % 4 === 0 ? recipients : Math.round(recipients * 0.985);
    const delivered = scenario === 'extreme' && i % 3 === 0 ? sent : Math.round(sent * (0.91 + (i % 7) / 100));
    const read = scenario === 'extreme' && i % 5 === 0 ? 0 : Math.round(delivered * (0.42 + (i % 5) / 20));
    const failed = Math.max(0, recipients - sent + (scenario === 'extreme' ? i * 87 : i * 5));
    return { id: `preview-${scenario}-${i}`, name: i % 6 === 0 ? `${long} #${i + 1}` : `Campanha ${scenario} #${i + 1}`, status: i % 5 === 0 ? 'failed' : i % 4 === 0 ? 'running' : 'completed', provider_id: 'preview-provider', template_id: `template-${i % 9}`, template_name: i % 4 === 0 ? `${long} Template ${i}` : `Template ${i % 9}`, template_category: i % 2 ? 'MARKETING' : 'UTILITY', template_language: i % 3 ? 'pt_BR' : 'en_US', total_recipients: recipients, total_sent: sent, total_delivered: delivered, total_read: read, total_failed: failed, delivery_rate: sent ? delivered / sent * 100 : null, read_rate: delivered ? read / delivered * 100 : null, failure_rate: recipients ? failed / recipients * 100 : null, started_at: new Date(Date.now() - i * 86400000).toISOString(), duration_seconds: 600 + i * 35, created_at: new Date().toISOString(), updated_at: new Date().toISOString() } as any;
  });
  const summary: CampaignAnalyticsSummary = items.reduce((acc, c: any) => ({ ...acc, campaigns_created: size, campaigns_completed: items.filter((x: any) => x.status === 'completed').length, total_recipients: acc.total_recipients + c.total_recipients, total_sent: acc.total_sent + c.total_sent, total_delivered: acc.total_delivered + c.total_delivered, total_read: acc.total_read + c.total_read, total_failed: acc.total_failed + c.total_failed }), { campaigns_created: size, campaigns_completed: 0, total_recipients: 0, total_sent: 0, total_delivered: 0, total_read: 0, total_failed: 0, delivery_rate: null, read_rate: null, failure_rate: null });
  summary.delivery_rate = summary.total_sent ? summary.total_delivered / summary.total_sent * 100 : null; summary.read_rate = summary.total_delivered ? summary.total_read / summary.total_delivered * 100 : null; summary.failure_rate = summary.total_recipients ? summary.total_failed / summary.total_recipients * 100 : null;
  const timeline: TimelineAnalytics = { grain: 'day', items: Array.from({ length: scenario === 'high' ? 90 : 30 }, (_, i) => ({ bucket: new Date(Date.now() - (29 - i) * 86400000).toISOString(), sent: Math.round(multiplier * (5 + i % 9)), delivered: Math.round(multiplier * (4.7 + i % 8)), read: scenario === 'extreme' && i % 6 === 0 ? 0 : Math.round(multiplier * (2.8 + i % 5)), failed: Math.round(multiplier * (0.1 + (i % 4) / 10)) })) };
  const templates: TemplateAnalyticsRow[] = Array.from({ length: scenario === 'high' ? 18 : 8 }, (_, i) => ({ template_id: `t-${i}`, template_name: i % 5 ? `Template ${i}` : `${long} ${i}`, category: i % 2 ? 'MARKETING' : 'UTILITY', language: i % 3 ? 'pt_BR' : 'es', campaigns: 1 + i * 2, total_recipients: multiplier * (i + 1), total_sent: multiplier * i, total_delivered: multiplier * i * .93, total_read: multiplier * i * .58, total_failed: multiplier * i * .04, delivery_rate: 93 - i / 5, read_rate: 58 - i }));
  const failures: FailureAnalyticsRow[] = ['Telefone inválido', 'Usuário bloqueou', 'Janela expirada', 'Template rejeitado', 'Limite do provedor'].map((category, i) => ({ category, message: category, recommendation: ['Revise código do país e formatação.', 'Evite reenvios imediatos e monitore opt-out.', 'Reative conversa com template aprovado.', 'Verifique variáveis e política da Meta.', 'Distribua o envio em janelas menores.'][i], count: Math.round(multiplier * (5 - i) / 8), percent: (5 - i) * 12, codes: [`WZ-${400 + i}`, `META-${1000 + i}`] }));
  const heatmap: HeatmapAnalytics = { sufficient_data: scenario !== 'low', items: Array.from({ length: 7 * 24 }, (_, i) => ({ weekday: Math.floor(i / 24), hour: i % 24, count: Math.round((i % 24) * (1 + i % 7) * multiplier / 200) })) };
  return { summary, campaigns: { items: items.slice(0, 20), page: 1, page_size: 20, total: size } as CampaignAnalyticsPage, templates, timeline, failures, heatmap };
}
