import os

WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID") or os.getenv("PHONE_NUMBER_ID")
if not WHATSAPP_PHONE_NUMBER_ID:
    raise Exception("PHONE_NUMBER_ID não configurado")
print("[PHONE ID]:", WHATSAPP_PHONE_NUMBER_ID)
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN")
