import { useState } from 'react';
import { automationShare } from './catalog';
import type { AIStoreCardData, AIStoreTemplateMeta, KitVersion } from './types';
const standardTabs = ['Visão geral','Arquitetura','Nodes','Instalação','Aprender','Versões','Dependências'] as const;
const kitTabs = ['Visão geral','Como esta operação funciona','Templates','CRM & Pipeline','Dashboards','Documentação','Academy','Instalação'] as const;
const versionNames: readonly KitVersion[] = ['Sem IA','Híbrida','IA Completa'];
const List = ({ title, items }: { title: string; items: readonly string[] }) => <section className="business-kit-panel"><h4>{title}</h4><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section>;
export default function AISystemDetailsModal({ card, template, onBack, onClose, onInstall }: { card: AIStoreCardData; template?: AIStoreTemplateMeta; onBack: () => void; onClose: () => void; onInstall: (id: string) => void }) {
  const kit = card.businessKit; const tabs = kit ? kitTabs : standardTabs; const [tab,setTab] = useState<string>('Visão geral'); const [selectedNode,setSelectedNode] = useState(card.nodes[0]); const [version,setVersion] = useState<KitVersion>('Híbrida'); const [installed,setInstalled] = useState(false); const share = automationShare(card); const education = card.nodeEducation[selectedNode];
  const install = () => { onInstall(card.id); if (kit) setInstalled(true); };
  return <div className="ai-store-details-backdrop" role="presentation" onMouseDown={onClose}><section className="ai-system-details-modal" role="dialog" aria-modal="true" aria-label={`Detalhes de ${card.title}`} onMouseDown={(e) => e.stopPropagation()}>
    <header className="ai-system-details-header"><button type="button" className="ai-store-back-button" onClick={onBack}>← Catálogo</button><button type="button" className="ai-store-close-button" onClick={onClose} aria-label="Fechar detalhes">×</button></header>
    <div className="ai-system-details-hero"><div className="ai-system-details-icon">{card.icon}</div><div><span className="ai-store-eyebrow">{card.marketplaceType} · {card.segment}</span><h3>{card.title}</h3><p>{card.subtitle}</p></div></div>
    {kit && <div className="business-kit-facts"><span><b>Implantação</b>{kit.implementationTime}</span><span><b>Complexidade</b>{kit.complexity}</span><span><b>Segmento</b>{card.segment}</span><span><b>Versão escolhida</b>{version}</span></div>}
    <nav className="ai-store-detail-tabs" aria-label="Detalhes do item">{tabs.map((value) => <button type="button" key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{value}</button>)}</nav>
    <div className="ai-store-detail-content">
      {tab === 'Visão geral' && (kit ? <><div className="ai-system-details-grid"><section><h4>Problema que resolve</h4><p>{kit.problem}</p></section><section><h4>Resultado esperado</h4><p>{kit.expectedOutcome}</p></section></div><h4>Versões disponíveis</h4><div className="business-kit-versions">{versionNames.map((name) => <button key={name} className={version === name ? 'active' : ''} onClick={() => setVersion(name)}><strong>{name}</strong>{kit.versions[name].map((change) => <span key={change}>✓ {change}</span>)}</button>)}</div><section className="consultant-mode"><h4>Por que recomendamos esta estratégia?</h4>{kit.consultantRationale.map((reason) => <p key={reason}>“{reason}”</p>)}</section><h4>Metodologias reutilizáveis</h4><div className="methodology-grid">{kit.methodologies.map((item) => <article key={item.id}><b>{item.name}</b><small>v{item.version} · {version}</small><p>{item.purpose}</p><span>{item.variants[version]}</span></article>)}</div></> : <div className="ai-system-details-grid"><section><h4>Objetivo</h4><p>{card.details}</p></section><section><h4>Resumo técnico</h4><p>{card.nodes.length} nodes · {card.setupTime} · {card.difficulty} · versão {template?.version || card.version}</p><p>Automação tradicional {share.traditional}% · IA {share.ai}%</p></section></div>)}
      {kit && tab === 'Como esta operação funciona' && <div className="strategy-timeline">{kit.strategy.map((stage,index) => <article key={stage.name}><span>{index + 1}</span><div><h4>{stage.name}</h4><p><b>Objetivo:</b> {stage.objective}</p><p><b>Por que existe:</b> {stage.rationale}</p><p><b>Resultado:</b> {stage.outcome}</p><small>Indicadores: {stage.indicators.join(' · ')}</small></div></article>)}</div>}
      {kit && tab === 'Templates' && <><h4>Biblioteca de copies · {card.segment}</h4><div className="copy-library">{kit.copies.map((copy) => <article key={copy.category}><b>{copy.category}</b><p>{copy.text}</p></article>)}</div></>}
      {kit && tab === 'CRM & Pipeline' && <div className="business-kit-columns"><List title="Campos personalizados" items={kit.crmFields}/><List title="Pipeline" items={kit.pipeline}/><List title="Tags automáticas" items={kit.tags}/><List title="Base de conhecimento inicial" items={kit.knowledgeBase}/></div>}
      {kit && tab === 'Dashboards' && <div className="business-kit-columns"><List title="Dashboards instalados" items={kit.dashboards}/><List title="KPIs acompanhados" items={kit.kpis}/></div>}
      {kit && tab === 'Documentação' && <List title="Documentação da operação" items={kit.documentation}/>} {kit && tab === 'Academy' && <List title="Treinamento específico" items={kit.academy}/>}
      {tab === 'Arquitetura' && <div className="ai-store-graph" aria-label="Grafo somente leitura">{card.nodes.map((node,index) => <button type="button" key={`${node}-${index}`} className={/AI|RAG/.test(node) ? 'uses-ai' : ''} onClick={() => setSelectedNode(node)}><span>{index + 1}</span>{node}</button>)}</div>}
      {tab === 'Nodes' && <div className="ai-store-node-layout"><div className="ai-store-node-list">{card.nodes.map((node,index) => <button type="button" key={`${node}-${index}`} className={selectedNode === node ? 'active' : ''} onClick={() => setSelectedNode(node)}>{node}</button>)}</div><section><h4>{selectedNode}</h4><p>{education?.summary}</p><strong>Propósito</strong><p>{education?.purpose}</p><strong>Por que existe aqui</strong><p>{education?.why_here}</p><strong>Uso de IA</strong><p>{education?.ai_usage}</p></section></div>}
      {tab === 'Instalação' && (installed && kit ? <section className="post-install-checklist"><h4>Kit instalado · Checklist pós-instalação</h4><p>A instalação criou cópias editáveis usando o runtime e os componentes existentes do Wazza.</p>{kit.checklist.map((item) => <label key={item}><input type="checkbox" defaultChecked={item === 'WhatsApp conectado'}/><span>{item}</span></label>)}</section> : <section><h4>Preview da instalação · {version}</h4><pre>{JSON.stringify({...card.installManifest, selected_version: version},null,2)}</pre><p><strong>Confirmação obrigatória:</strong> nenhuma integração externa será conectada silenciosamente.</p></section>)}
      {tab === 'Aprender' && <section><h4>Engenharia reversa</h4><p>Compreenda a composição, entradas, decisões, fallbacks e saídas antes de duplicar. Estes metadados educacionais não alteram a execução.</p></section>}
      {tab === 'Versões' && <section><h4>Versões disponíveis</h4><p><strong>{card.version}</strong> · {card.automationLevel} · a instalação cria uma cópia editável.</p></section>}
      {tab === 'Dependências' && <section><h4>Integrações e dependências</h4><div className="ai-store-integrations">{(card.integrations.length ? card.integrations : ['Nenhuma']).map((item) => <span key={item}>{item}</span>)}</div></section>}
    </div><footer className="ai-system-details-footer"><button type="button" className="ai-store-back-button" onClick={() => setTab(kit ? 'Academy' : 'Aprender')}>Aprender</button><button type="button" className="ai-store-install" onClick={install}>{installed ? 'Instalado' : `Instalar ${kit ? version : ''}`}</button></footer>
  </section></div>;
}
